import hashlib
from datetime import date
from urllib.parse import urlparse

# (theme_name, author) — slug вычисляется как theme_name.lower()
THEME_SLOTS: dict[int, list[tuple[str, str]]] = {
    1: [
        ("Clearwater",  "WebCraft Studio"),
        ("Northgate",   "PixelNest Labs"),
        ("Silverleaf",  "BrightPath Dev"),
        ("Ironwood",    "NovaBridge Co"),
        ("Amberfield",  "AmberDigital Studio"),
        ("Amberwood",   "AmberWeb Labs"),
        ("Ambervale",   "AmberCode Dev"),
        ("Ambergate",   "AmberTech Co"),
        ("Amberbrook",  "AmberSoft HQ"),
        ("Ambermere",   "AmberApp Works"),
    ],
    2: [
        ("Brightfield", "SwiftIsle Studio"),
        ("Stonepath",   "CoreEdge Labs"),
        ("Cedarway",    "ForgeGrid Dev"),
        ("Hollowbrook", "HubWorks Digital"),
        ("Birchdale",   "BirchDigital Studio"),
        ("Birchwood",   "BirchWeb Labs"),
        ("Birchfield",  "BirchCode Dev"),
        ("Birchgrove",  "BirchTech Co"),
        ("Birchgate",   "BirchSoft HQ"),
        ("Birchbrook",  "BirchApp Works"),
    ],
    3: [
        ("Veridian",    "LumenCraft Studio"),
        ("Ashford",     "MintNord Labs"),
        ("Pinecrest",   "OpenPure Dev"),
        ("Riverton",    "QuickRoot Co"),
        ("Cliffdale",   "CliffDigital Studio"),
        ("Cliffwood",   "CliffWeb Labs"),
        ("Cliffside",   "CliffCode Dev"),
        ("Cliffgate",   "CliffTech Co"),
        ("Cliffbrook",  "CliffSoft HQ"),
        ("Cliffmere",   "CliffApp Works"),
    ],
    4: [
        ("Goldenvale",  "SkyTide Studio"),
        ("Elmwood",     "UltraVox Labs"),
        ("Fairhaven",   "WaveXen Dev"),
        ("Crestwood",   "ZenithApex Co"),
        ("Cloverdale",  "CloverDigital Studio"),
        ("Cloverwood",  "CloverWeb Labs"),
        ("Cloverfield", "CloverCode Dev"),
        ("Clovergate",  "CloverTech Co"),
        ("Cloverbrook", "CloverSoft HQ"),
        ("Clovermere",  "CloverApp Works"),
    ],
    5: [
        ("Blueridge",   "BlueCraft Studio"),
        ("Mapleton",    "DeepEcho Labs"),
        ("Sunridge",    "CoreBay Dev"),
        ("Fernwick",    "DawnCove Co"),
        ("Dawnfield",   "DawnDigital Studio"),
        ("Dawnwood",    "DawnWeb Labs"),
        ("Dawnbrook",   "DawnCode Dev"),
        ("Dawngate",    "DawnTech Co"),
        ("Dawnmere",    "DawnSoft HQ"),
        ("Dawnvale",    "DawnApp Works"),
    ],
    6: [
        ("Lakeview",    "PixelForge Studio"),
        ("Thornbury",   "BrightIsle Labs"),
        ("Willowmere",  "NovaField Dev"),
        ("Stonebridge", "WebWorks Co"),
        ("Deepwood",    "DeepDigital Studio"),
        ("Deepfield",   "DeepWeb Labs"),
        ("Deepgate",    "DeepCode Dev"),
        ("Deepbrook",   "DeepTech Co"),
        ("Deepmere",    "DeepSoft HQ"),
        ("Deepvale",    "DeepApp Works"),
    ],
    7: [
        ("Oakshire",    "SwiftCraft Studio"),
        ("Meadowlark",  "ClearEdge Labs"),
        ("Copperfield", "BoldGate Dev"),
        ("Harborview",  "PeakHive Co"),
        ("Driftwood",   "DriftDigital Studio"),
        ("Driftfield",  "DriftWeb Labs"),
        ("Driftgate",   "DriftCode Dev"),
        ("Driftbrook",  "DriftTech Co"),
        ("Driftmere",   "DriftSoft HQ"),
        ("Driftvale",   "DriftApp Works"),
    ],
    8: [
        ("Crystalpath", "CoreLoft Studio"),
        ("Whitmore",    "EdgeMoss Labs"),
        ("Foxhill",     "GridNet Dev"),
        ("Greengate",   "HubOak Co"),
        ("Emberfield",  "EmberDigital Studio"),
        ("Emberwood",   "EmberWeb Labs"),
        ("Embervale",   "EmberCode Dev"),
        ("Embergate",   "EmberTech Co"),
        ("Emberbrook",  "EmberSoft HQ"),
        ("Embermere",   "EmberApp Works"),
    ],
    9: [
        ("Blackwater",  "InnoPort Studio"),
        ("Summitview",  "KeenQuest Labs"),
        ("Arbordale",   "LumenReef Dev"),
        ("Redwood",     "MintSand Co"),
        ("Farndale",    "FarnDigital Studio"),
        ("Farnwood",    "FarnWeb Labs"),
        ("Farnfield",   "FarnCode Dev"),
        ("Farngate",    "FarnTech Co"),
        ("Farnbrook",   "FarnSoft HQ"),
        ("Farnmere",    "FarnApp Works"),
    ],
    10: [
        ("Silvergate",  "NordTree Studio"),
        ("Northbrook",  "OpenUnion Labs"),
        ("Clayfield",   "PureVale Dev"),
        ("Pinehurst",   "QuickWard Co"),
        ("Flintwood",   "FlintDigital Studio"),
        ("Flintfield",  "FlintWeb Labs"),
        ("Flintgate",   "FlintCode Dev"),
        ("Flintbrook",  "FlintTech Co"),
        ("Flintmere",   "FlintSoft HQ"),
        ("Flintvale",   "FlintApp Works"),
    ],
    11: [
        ("Brightwood",  "RootYard Studio"),
        ("Swiftwater",  "SkyZone Labs"),
        ("Irongate",    "TideApex Dev"),
        ("Goldenshore", "UltraBlue Co"),
        ("Forestfield", "ForestDigital Studio"),
        ("Forestgate",  "ForestWeb Labs"),
        ("Forestbrook", "ForestCode Dev"),
        ("Forestmere",  "ForestTech Co"),
        ("Forestvale",  "ForestSoft HQ"),
        ("Forestwood",  "ForestApp Works"),
    ],
    12: [
        ("Cedarbrook",  "VoxCraft Studio"),
        ("Stonehaven",  "WaveDeep Labs"),
        ("Wildfield",   "XenEcho Dev"),
        ("Ashgrove",    "ZenithBay Co"),
        ("Frostwood",   "FrostDigital Studio"),
        ("Frostfield",  "FrostWeb Labs"),
        ("Frostgate",   "FrostCode Dev"),
        ("Frostbrook",  "FrostTech Co"),
        ("Frostmere",   "FrostSoft HQ"),
        ("Frostvale",   "FrostApp Works"),
    ],
    13: [
        ("Bluehaven",   "PixelCove Studio"),
        ("Maplecrest",  "BrightDawn Labs"),
        ("Riverwalk",   "NovaForge Dev"),
        ("Fernbrook",   "WebGrid Co"),
        ("Glendale",    "GlenDigital Studio"),
        ("Glenfield",   "GlenWeb Labs"),
        ("Glenhaven",   "GlenCode Dev"),
        ("Glenwood",    "GlenTech Co"),
        ("Glengate",    "GlenSoft HQ"),
        ("Glenmere",    "GlenApp Works"),
    ],
    14: [
        ("Lakestone",   "SwiftHub Studio"),
        ("Thorndale",   "ClearInno Labs"),
        ("Willowgate",  "BoldKeen Dev"),
        ("Crestbury",   "PeakLumen Co"),
        ("Greystone",   "GreyDigital Studio"),
        ("Greyfield",   "GreyWeb Labs"),
        ("Greygate",    "GreyCode Dev"),
        ("Greybrook",   "GreyTech Co"),
        ("Greymere",    "GreySoft HQ"),
        ("Greywood",    "GreyApp Works"),
    ],
    15: [
        ("Oakdale",     "CoreMint Studio"),
        ("Meadowview",  "EdgeNord Labs"),
        ("Coppergate",  "GridOpen Dev"),
        ("Harborstone", "HubPure Co"),
        ("Hawthorne",   "HazelDigital Studio"),
        ("Hazeldene",   "HazelWeb Labs"),
        ("Hazelwood",   "HazelCode Dev"),
        ("Hazelgate",   "HazelTech Co"),
        ("Hazelbrook",  "HazelSoft HQ"),
        ("Hazelmere",   "HazelApp Works"),
    ],
    16: [
        ("Crystalbrook","InnoQuick Studio"),
        ("Whitfield",   "KeenRoot Labs"),
        ("Foxdale",     "LumenSky Dev"),
        ("Greenpath",   "MintTide Co"),
        ("Heathfield",  "HeathDigital Studio"),
        ("Heatherdale", "HeathWeb Labs"),
        ("Heathgate",   "HeathCode Dev"),
        ("Heathwood",   "HeathTech Co"),
        ("Heathbrook",  "HeathSoft HQ"),
        ("Heathmere",   "HeathApp Works"),
    ],
    17: [
        ("Blackhill",   "NordUltra Studio"),
        ("Summitgate",  "OpenVox Labs"),
        ("Arborview",   "PureWave Dev"),
        ("Redpath",     "QuickXen Co"),
        ("Hillcrest",   "HillDigital Studio"),
        ("Hillside",    "HillWeb Labs"),
        ("Hillgate",    "HillCode Dev"),
        ("Hillwood",    "HillTech Co"),
        ("Hillbrook",   "HillSoft HQ"),
        ("Hillmere",    "HillApp Works"),
    ],
    18: [
        ("Silverbrook", "RootZenith Studio"),
        ("Northdale",   "SkyApex Labs"),
        ("Claystone",   "TideBlue Dev"),
        ("Pinewood",    "UltraCraft Co"),
        ("Ivywood",     "IvyDigital Studio"),
        ("Ivymere",     "IvyWeb Labs"),
        ("Ivygate",     "IvyCode Dev"),
        ("Ivyfield",    "IvyTech Co"),
        ("Ivybrook",    "IvySoft HQ"),
        ("Ivyvale",     "IvyApp Works"),
    ],
    19: [
        ("Brightgate",  "VoxDeep Studio"),
        ("Swiftfield",  "WaveEcho Labs"),
        ("Ironcrest",   "XenBay Dev"),
        ("Goldenbrook", "ZenithCove Co"),
        ("Jadehaven",   "JadeDigital Studio"),
        ("Jadefield",   "JadeWeb Labs"),
        ("Jadewood",    "JadeCode Dev"),
        ("Jadebrook",   "JadeTech Co"),
        ("Jademere",    "JadeSoft HQ"),
        ("Jadevale",    "JadeApp Works"),
    ],
    20: [
        ("Cedarfield",  "PixelDawn Studio"),
        ("Stonecrest",  "BrightForge Labs"),
        ("Wildpath",    "NovaGrid Dev"),
        ("Ashhaven",    "WebHub Co"),
        ("Knollfield",  "KnollDigital Studio"),
        ("Knollwood",   "KnollWeb Labs"),
        ("Knollgate",   "KnollCode Dev"),
        ("Knollbrook",  "KnollTech Co"),
        ("Knollmere",   "KnollSoft HQ"),
        ("Knollvale",   "KnollApp Works"),
    ],
    21: [
        ("Bluegate",    "SwiftInno Studio"),
        ("Maplehaven",  "ClearKeen Labs"),
        ("Riverstone",  "BoldLumen Dev"),
        ("Ferngate",    "PeakMint Co"),
        ("Laurelwood",  "LaurelDigital Studio"),
        ("Laurelfield", "LaurelWeb Labs"),
        ("Laurelgate",  "LaurelCode Dev"),
        ("Laurelbrook", "LaurelTech Co"),
        ("Laurelmere",  "LaurelSoft HQ"),
        ("Laurelvale",  "LaurelApp Works"),
    ],
    22: [
        ("Lakepath",    "CoreNord Studio"),
        ("Thornwood",   "EdgeOpen Labs"),
        ("Willowbrook", "GridPure Dev"),
        ("Crestfield",  "HubQuick Co"),
        ("Larchwood",   "LarchDigital Studio"),
        ("Larchdale",   "LarchWeb Labs"),
        ("Larchfield",  "LarchCode Dev"),
        ("Larchgate",   "LarchTech Co"),
        ("Larchbrook",  "LarchSoft HQ"),
        ("Larchmere",   "LarchApp Works"),
    ],
    23: [
        ("Oakstone",    "InnoRoot Studio"),
        ("Meadowgate",  "KeenSky Labs"),
        ("Copperbrook", "LumenTide Dev"),
        ("Harborfield", "MintUltra Co"),
        ("Marshfield",  "MarshDigital Studio"),
        ("Marshgate",   "MarshWeb Labs"),
        ("Marshwood",   "MarshCode Dev"),
        ("Marshbrook",  "MarshTech Co"),
        ("Marshmere",   "MarshSoft HQ"),
        ("Marshvale",   "MarshApp Works"),
    ],
    24: [
        ("Crystalfield","NordVox Studio"),
        ("Whitford",    "OpenWave Labs"),
        ("Foxbrook",    "PureXen Dev"),
        ("Greenstone",  "QuickZenith Co"),
        ("Millbrook",   "MillDigital Studio"),
        ("Millfield",   "MillWeb Labs"),
        ("Millgate",    "MillCode Dev"),
        ("Millwood",    "MillTech Co"),
        ("Millmere",    "MillSoft HQ"),
        ("Millvale",    "MillApp Works"),
    ],
    25: [
        ("Blackfield",  "RootApex Studio"),
        ("Summitbrook", "SkyBlue Labs"),
        ("Arborgate",   "TideCraft Dev"),
        ("Redbrook",    "UltraDeep Co"),
        ("Moorfield",   "MoorDigital Studio"),
        ("Moorgate",    "MoorWeb Labs"),
        ("Moorwood",    "MoorCode Dev"),
        ("Moorbrook",   "MoorTech Co"),
        ("Moormere",    "MoorSoft HQ"),
        ("Moorvale",    "MoorApp Works"),
    ],
    26: [
        ("Silverpath",  "VoxEcho Studio"),
        ("Northfield",  "WaveBay Labs"),
        ("Clayhaven",   "XenCove Dev"),
        ("Pinegate",    "ZenithDawn Co"),
        ("Mossfield",   "MossDigital Studio"),
        ("Mossgate",    "MossWeb Labs"),
        ("Mosswood",    "MossCode Dev"),
        ("Mossbrook",   "MossTech Co"),
        ("Mossmere",    "MossSoft HQ"),
        ("Mossvale",    "MossApp Works"),
    ],
    27: [
        ("Brighthaven", "PixelFlow Studio"),
        ("Swiftbrook",  "BrightLoft Labs"),
        ("Ironpath",    "NovaPort Dev"),
        ("Goldengate",  "WebReef Co"),
        ("Oakfield",    "OakDigital Studio"),
        ("Oakgate",     "OakWeb Labs"),
        ("Oakgrove",    "OakCode Dev"),
        ("Oakbrook",    "OakTech Co"),
        ("Oakmere",     "OakSoft HQ"),
        ("Oakvale",     "OakApp Works"),
    ],
    28: [
        ("Cedarstone",  "SwiftTree Studio"),
        ("Stonebrook",  "ClearBay Labs"),
        ("Wildgate",    "BoldNest Dev"),
        ("Ashbrook",    "PeakPath Co"),
        ("Pinegrove",   "PineDigital Studio"),
        ("Pinefield",   "PineWeb Labs"),
        ("Pinebrook",   "PineCode Dev"),
        ("Pinemere",    "PineTech Co"),
        ("Pinevale",    "PineSoft HQ"),
        ("Pinedale",    "PineApp Works"),
    ],
    29: [
        ("Bluefield",   "CoreBridge Studio"),
        ("Maplegate",   "EdgeCraft Labs"),
        ("Rivergate",   "GridStorm Dev"),
        ("Fernwood",    "HubField Co"),
        ("Ravendale",   "RavenDigital Studio"),
        ("Ravenwood",   "RavenWeb Labs"),
        ("Ravenfield",  "RavenCode Dev"),
        ("Ravengate",   "RavenTech Co"),
        ("Ravenbrook",  "RavenSoft HQ"),
        ("Ravenmere",   "RavenApp Works"),
    ],
    30: [
        ("Lakebrook",   "InnoWorks Studio"),
        ("Thornfield",  "KeenFlow Labs"),
        ("Willowpath",  "LumenGate Dev"),
        ("Crestgate",   "MintHive Co"),
        ("Rockfield",   "RockDigital Studio"),
        ("Rockgate",    "RockWeb Labs"),
        ("Rockwood",    "RockCode Dev"),
        ("Rockbrook",   "RockTech Co"),
        ("Rockmere",    "RockSoft HQ"),
        ("Rockvale",    "RockApp Works"),
    ],
    31: [
        ("Oakwood",     "NordLoft Studio"),
        ("Meadowbrook", "OpenMoss Labs"),
        ("Copperstone", "PureNet Dev"),
        ("Harborgate",  "QuickOak Co"),
        ("Rosewood",    "RoseDigital Studio"),
        ("Rosefield",   "RoseWeb Labs"),
        ("Rosegate",    "RoseCode Dev"),
        ("Rosebrook",   "RoseTech Co"),
        ("Rosemere",    "RoseSoft HQ"),
        ("Rosevale",    "RoseApp Works"),
    ],
}


def get_theme_identity(site_url: str) -> dict:
    """Return {name, slug, author} for the current day, seeded by domain."""
    domain  = urlparse(site_url).netloc or site_url
    day     = date.today().day
    options = THEME_SLOTS[day]
    h       = int(hashlib.md5(domain.encode()).hexdigest(), 16)
    name, author = options[h % len(options)]
    return {"name": name, "slug": name.lower(), "author": author}
