#!/usr/bin/env bash
# Generated by pipeline — do not edit manually
# Site: Site Name | http://localhost:8083

wp() { command wp --allow-root "$@"; }

# Patch wp-config.php for HTTPS proxy (Nginx Proxy Manager)
if ! grep -q "HTTP_X_FORWARDED_PROTO" wp-config.php; then
    sed -i "2i // Proxy SSL Fix\nif (isset(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') { \$_SERVER['HTTPS'] = 'on'; }\n" wp-config.php
fi

if [ ! -f wp-config.php ]; then
    echo "Error: run this script from the WordPress root directory!"
    exit 1
fi

SITE_URL="http://localhost:8083"
SITE_TITLE="Site Name"
ADMIN_USER="admin"
ADMIN_EMAIL="admin@domen.com"
THEME_SLUG="utheme"
WP_LANG="en_US"

ADMIN_PASS=$(tr -dc 'a-zA-Z0-9!@#$%^&*()_+=-' < /dev/urandom | head -c 30)

echo "--- WP Auto-Setup: $SITE_TITLE ---"

# ===========================================================================
# 1. INSTALL WORDPRESS

wp core install \
    --url="$SITE_URL" \
    --title="Initial Setup" \
    --admin_user="$ADMIN_USER" \
    --admin_password="$ADMIN_PASS" \
    --admin_email="$ADMIN_EMAIL" \
    --skip-email

wp language core install $WP_LANG --activate
echo "Language set to $WP_LANG."

# ===========================================================================
# 2. ADMIN USER

FIRST_NAME="Editorial Team"
LAST_NAME="«$SITE_TITLE»"
DISPLAY_NAME="$FIRST_NAME $LAST_NAME"

if wp user get "$ADMIN_USER" > /dev/null 2>&1; then
    wp user update "$ADMIN_USER" \
        --user_pass="$ADMIN_PASS" \
        --role=administrator \
        --display_name="$DISPLAY_NAME" \
        --first_name="$FIRST_NAME" \
        --last_name="$LAST_NAME"
else
    wp user create "$ADMIN_USER" "$ADMIN_EMAIL" \
        --user_pass="$ADMIN_PASS" \
        --role=administrator \
        --display_name="$DISPLAY_NAME" \
        --first_name="$FIRST_NAME" \
        --last_name="$LAST_NAME"
fi

ADMIN_ID=$(wp user get "$ADMIN_USER" --field=ID)
wp user update 1 --locale=en_US
echo "Admin user ready (ID: $ADMIN_ID)."

# ===========================================================================
# 3. THEME

wp theme activate $THEME_SLUG
wp theme list --status=inactive --field=name | while read -r _theme; do wp theme delete "$_theme"; done
echo "Theme '$THEME_SLUG' activated."

# ===========================================================================
# 4. CLEANUP DEFAULT CONTENT

wp post delete $(wp post list --post_type=post,page --format=ids) --force
wp eval "global \$wpdb;
    \$wpdb->query(\"TRUNCATE TABLE {\$wpdb->prefix}posts\");
    \$wpdb->query(\"TRUNCATE TABLE {\$wpdb->prefix}postmeta\");
    \$wpdb->query(\"TRUNCATE TABLE {\$wpdb->prefix}terms\");
    \$wpdb->query(\"TRUNCATE TABLE {\$wpdb->prefix}term_taxonomy\");
    \$wpdb->query(\"TRUNCATE TABLE {\$wpdb->prefix}term_relationships\");"
echo "Default content removed."

# ===========================================================================
# 5. SETTINGS

wp eval "
global \$wp_rewrite;
update_option('blogname', base64_decode('U2l0ZSBOYW1l'));
\$wp_rewrite->set_permalink_structure('/%postname%/');
\$wp_rewrite->flush_rules(true);
update_option('default_pingback_flag', 0);
update_option('default_ping_status', 'closed');
update_option('default_comment_status', 'closed');
update_option('require_name_email', 1);
update_option('comment_registration', 1);
update_option('close_comments_for_old_posts', 1);
update_option('thread_comments', 1);
update_option('thread_comments_depth', 5);
update_option('page_comments', 1);
update_option('comments_per_page', 50);
update_option('default_comments_page', 'newest');
update_option('moderation_notify', 0);
update_option('comments_notify', 0);
update_option('comment_moderation', 1);
update_option('comment_whitelist', 1);
update_option('uploads_use_yearmonth_folders', 0);
update_user_meta($ADMIN_ID, 'edit_post_per_page', 200);
update_user_meta($ADMIN_ID, 'edit_page_per_page', 200);
"
echo "Settings applied."

# ===========================================================================
# 6. CATEGORIES

wp eval "
wp_insert_term('Utility Pages', 'category');
wp_insert_term('page+5', 'category');
wp_insert_term('page+30', 'category');
wp_insert_term('news', 'category');
"
echo "Categories created."

# ===========================================================================
# 7. MEDIA IMPORT
# Медиа импортируются ДО создания страниц, чтобы знать attachment ID и URL
# для замены плейсхолдеров %%IMGID:file.webp%% и %%IMGSRC:file.webp%% в .wp файлах

echo "Importing media from /tmp/staging/images/ ..."
declare -A MEDIA_IDS   # filename → attachment_id
declare -A MEDIA_URLS  # filename → public URL

while IFS=$'\t' read -r _f1 _f2 _f3; do
    if [ "$_f1" = "WARN" ]; then
        echo "  WARN: failed to import $_f2"
    else
        MEDIA_IDS["$_f1"]=$_f2
        MEDIA_URLS["$_f1"]=$_f3
        echo "  $_f1 → ID $_f2"
    fi
done < <(wp eval "
ob_start();
require_once ABSPATH . 'wp-admin/includes/media.php';
require_once ABSPATH . 'wp-admin/includes/file.php';
require_once ABSPATH . 'wp-admin/includes/image.php';
\$results = [];
foreach (glob('/tmp/staging/images/*') as \$file) {
    if (!is_file(\$file)) continue;
    \$fname = basename(\$file);
    \$arr   = ['name' => \$fname, 'tmp_name' => \$file];
    \$id    = media_handle_sideload(\$arr, 0);
    if (is_wp_error(\$id)) {
        \$results[] = 'WARN' . chr(9) . \$fname . chr(9) . '';
        continue;
    }
    \$results[] = \$fname . chr(9) . \$id . chr(9) . wp_get_attachment_url(\$id);
}
ob_end_clean();
echo implode(chr(10), \$results) . chr(10);
" 2>/dev/null)

if [ -n "${MEDIA_IDS[favicon.png]}" ]; then
    wp option update site_icon ${MEDIA_IDS[favicon.png]}
    echo "  Favicon set (ID: ${MEDIA_IDS[favicon.png]})"
fi
if [ -n "${MEDIA_IDS[logo.webp]}" ]; then
    wp eval "set_theme_mod('custom_logo', ${MEDIA_IDS[logo.webp]});"
    echo "  Logo set (ID: ${MEDIA_IDS[logo.webp]})"
fi

# Заменяем плейсхолдеры в .wp файлах реальными ID и URL
echo "Resolving image placeholders in .wp files..."
for page_file in /tmp/staging/pages/*.wp; do
    [ -f "$page_file" ] || continue
    for fname in "${!MEDIA_IDS[@]}"; do
        img_id=${MEDIA_IDS[$fname]}
        img_url=${MEDIA_URLS[$fname]}
        sed -i "s@%%IMGID:${fname}%%@${img_id}@g" "$page_file"
        sed -i "s@%%IMGSRC:${fname}%%@${img_url}@g" "$page_file"
    done
done
echo "Placeholders resolved."

# ===========================================================================
# 8. PAGES
# Каждая страница создаётся одним wp eval: wp_insert_post + мета + категории.
# ob_start/ob_end_clean подавляет любой побочный вывод WP; echo $id — единственный stdout.
# Текстовые данные передаются через base64, избегая конфликтов bash/PHP экранирования.

declare -A PAGE_IDS

# --- index ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgQmV0dGluZyDigJQgT2RkcywgR3JvdXBzICYgUHJlZGljdGlvbnMgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'index',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/index.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[hero-stadium-world-cup.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgQmV0dGluZyDigJQgT2RkcywgR3JvdXBzICYgUHJlZGljdGlvbnMgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgQmV0dGluZyDigJQgT2RkcywgR3JvdXBzICYgUHJlZGljdGlvbnMgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('WW91ciBjb21wbGV0ZSBXb3JsZCBDdXAgMjAyNiBiZXR0aW5nIGh1Yi4gT2RkcywgZ3JvdXAgYW5hbHlzaXMsIEFsbCBXaGl0ZXMgY292ZXJhZ2UsIGFuZCBleHBlcnQgcGlja3MgZnJvbSBhIHNlbmlvciBmb290YmFsbCBiZXR0aW5nIGFuYWx5c3Qu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[index]=$PAGE_ID
echo "  Created 'index' (ID: $PAGE_ID)"

# --- news ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('TmV3cw=='),
    'post_name'     => 'news',
    'post_status'   => 'publish',
    'post_content'  => '',
    'page_template' => 'page-list.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_custom_seo_title', base64_decode('TmV3cw=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[news]=$PAGE_ID
echo "  Created 'news' (ID: $PAGE_ID)"

# --- sitemap ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('U2l0ZW1hcA=='),
    'post_name'     => 'sitemap',
    'post_status'   => 'publish',
    'post_content'  => '',
    'page_template' => 'page-sitemap.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_custom_seo_title', base64_decode('U2l0ZW1hcA=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[sitemap]=$PAGE_ID
echo "  Created 'sitemap' (ID: $PAGE_ID)"

# --- world-cup-2026-betting-guide ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('SG93IHRvIEJldCBvbiB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIGEgUHVudGVyJ3MgR3VpZGUgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-betting-guide',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-betting-guide.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-betting-guide-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('SG93IHRvIEJldCBvbiB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIGEgUHVudGVyJ3MgR3VpZGUgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('SG93IHRvIEJldCBvbiB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIGEgUHVudGVyJ3MgR3VpZGUgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('TGVhcm4gaG93IHRvIGJldCBvbiB0aGUgMjAyNiBXb3JsZCBDdXAgd2l0aCB0aGlzIGhvbmVzdCBndWlkZS4gQmV0IHR5cGVzLCBzdHJhdGVneSwgYmFua3JvbGwgbWFuYWdlbWVudCwgYW5kIFRBQiBOWiB0aXBzIGZvciBLaXdpIHB1bnRlcnMu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-betting-guide]=$PAGE_ID
echo "  Created 'world-cup-2026-betting-guide' (ID: $PAGE_ID)"

# --- tab-nz-world-cup-betting ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('VEFCIE5aIFdvcmxkIEN1cCBCZXR0aW5nIOKAlCBIb25lc3QgS2l3aSBSZXZpZXcgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'tab-nz-world-cup-betting',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/tab-nz-world-cup-betting.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-betting-guide]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[tab-nz-world-cup-betting-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('VEFCIE5aIFdvcmxkIEN1cCBCZXR0aW5nIOKAlCBIb25lc3QgS2l3aSBSZXZpZXcgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('VEFCIE5aIFdvcmxkIEN1cCBCZXR0aW5nIOKAlCBIb25lc3QgS2l3aSBSZXZpZXcgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QW4gaG9uZXN0IGFzc2Vzc21lbnQgb2YgVEFCIE5aIGZvciBXb3JsZCBDdXAgMjAyNiBiZXR0aW5nLiBNYXJrZXRzLCBvZGRzIHF1YWxpdHksIGFuZCB3aGF0IEtpd2kgcHVudGVycyBzaG91bGQgZXhwZWN0Lg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[tab-nz-world-cup-betting]=$PAGE_ID
echo "  Created 'tab-nz-world-cup-betting' (ID: $PAGE_ID)"

# --- world-cup-2026-bet-types ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIEJldCBUeXBlcyDigJQgTWFya2V0cyBXb3J0aCBZb3VyIE1vbmV5IHwgS2lja09kZHM='),
    'post_name'     => 'world-cup-2026-bet-types',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-bet-types.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-betting-guide]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-bet-types-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIEJldCBUeXBlcyDigJQgTWFya2V0cyBXb3J0aCBZb3VyIE1vbmV5IHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIEJldCBUeXBlcyDigJQgTWFya2V0cyBXb3J0aCBZb3VyIE1vbmV5IHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QSBicmVha2Rvd24gb2YgV29ybGQgQ3VwIGJldHRpbmcgbWFya2V0cy4gT3V0cmlnaHQsIG1hdGNoLCBzcGVjaWFscywgYW5kIG11bHRpIGJldHMgcmF0ZWQgYnkgdmFsdWUgYW5kIGFjY2Vzc2liaWxpdHku'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-bet-types]=$PAGE_ID
echo "  Created 'world-cup-2026-bet-types' (ID: $PAGE_ID)"

# --- world-cup-2026-dark-horses ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgRGFyayBIb3JzZXMg4oCUIEZpdmUgVGVhbXMgdG8gV2F0Y2ggfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-dark-horses',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-dark-horses.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-betting-guide]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-dark-horses-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgRGFyayBIb3JzZXMg4oCUIEZpdmUgVGVhbXMgdG8gV2F0Y2ggfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgRGFyayBIb3JzZXMg4oCUIEZpdmUgVGVhbXMgdG8gV2F0Y2ggfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('Rml2ZSBkYXJrIGhvcnNlIHBpY2tzIGZvciB0aGUgMjAyNiBXb3JsZCBDdXAgd2l0aCBjb252aWN0aW9uIHJhdGluZ3MuIFBsdXMgdGhlIG92ZXJoeXBlZCB0ZWFtcyBJIGFtIGF2b2lkaW5nLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-dark-horses]=$PAGE_ID
echo "  Created 'world-cup-2026-dark-horses' (ID: $PAGE_ID)"

# --- world-cup-betting-glossary ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIEJldHRpbmcgR2xvc3Nhcnkg4oCUIFRlcm1zIEV4cGxhaW5lZCB8IEtpY2tPZGRz'),
    'post_name'     => 'world-cup-betting-glossary',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-betting-glossary.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-betting-guide]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-betting-glossary.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIEJldHRpbmcgR2xvc3Nhcnkg4oCUIFRlcm1zIEV4cGxhaW5lZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIEJldHRpbmcgR2xvc3Nhcnkg4oCUIFRlcm1zIEV4cGxhaW5lZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RXZlcnkgYmV0dGluZyB0ZXJtIGEgS2l3aSBwdW50ZXIgbmVlZHMgZm9yIHRoZSAyMDI2IFdvcmxkIEN1cC4gRnJvbSBhY2N1bXVsYXRvciB0byB2YWx1ZSBiZXQsIGluIHBsYWluIGxhbmd1YWdlLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-betting-glossary]=$PAGE_ID
echo "  Created 'world-cup-betting-glossary' (ID: $PAGE_ID)"

# --- world-cup-group-stage-betting ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('R3JvdXAgU3RhZ2UgQmV0dGluZyBTdHJhdGVneSBmb3IgdGhlIDIwMjYgV29ybGQgQ3VwIHwgS2lja09kZHM='),
    'post_name'     => 'world-cup-group-stage-betting',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-group-stage-betting.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-betting-guide]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-group-stage-betting-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('R3JvdXAgU3RhZ2UgQmV0dGluZyBTdHJhdGVneSBmb3IgdGhlIDIwMjYgV29ybGQgQ3VwIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('R3JvdXAgU3RhZ2UgQmV0dGluZyBTdHJhdGVneSBmb3IgdGhlIDIwMjYgV29ybGQgQ3VwIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('TXkgc3RyYXRlZ3kgZm9yIGdyb3VwIHN0YWdlIGJldHRpbmcgYXQgdGhlIDIwMjYgV29ybGQgQ3VwLiBNYXJrZXRzLCBwaWNrcywgYW5kIGxlc3NvbnMgZnJvbSBjb3ZlcmluZyB0aHJlZSB0b3VybmFtZW50cy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-group-stage-betting]=$PAGE_ID
echo "  Created 'world-cup-group-stage-betting' (ID: $PAGE_ID)"

# --- world-cup-history-betting-lessons ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIEJldHRpbmcgTGVzc29ucyBmcm9tIDIwMTggYW5kIDIwMjIgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-history-betting-lessons',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-history-betting-lessons.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-betting-guide]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-history-betting-lessons-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIEJldHRpbmcgTGVzc29ucyBmcm9tIDIwMTggYW5kIDIwMjIgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIEJldHRpbmcgTGVzc29ucyBmcm9tIDIwMTggYW5kIDIwMjIgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('V2hhdCBSdXNzaWEgMjAxOCBhbmQgUWF0YXIgMjAyMiB0YXVnaHQgbWUgYWJvdXQgYmV0dGluZy4gUGF0dGVybnMsIHVwc2V0cywgYW5kIHRocmVlIHJ1bGVzIGZvciAyMDI2Lg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-history-betting-lessons]=$PAGE_ID
echo "  Created 'world-cup-history-betting-lessons' (ID: $PAGE_ID)"

# --- world-cup-2026-groups-overview ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXBzIOKAlCBBbGwgMTIgQW5hbHlzZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-groups-overview',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-groups-overview.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-groups-overview-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXBzIOKAlCBBbGwgMTIgQW5hbHlzZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXBzIOKAlCBBbGwgMTIgQW5hbHlzZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QWxsIDEyIFdvcmxkIEN1cCAyMDI2IGdyb3VwcyByYXRlZCBmb3IgYmV0dGluZyB2YWx1ZS4gR3JvdXBzIG9mIGRlYXRoLCBvcGVuIGdyb3VwcywgYW5kIHRoZSBBbGwgV2hpdGVzJyBHcm91cCBHIGRpc3NlY3RlZC4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-groups-overview]=$PAGE_ID
echo "  Created 'world-cup-2026-groups-overview' (ID: $PAGE_ID)"

# --- bc-place-world-cup ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QkMgUGxhY2Ug4oCUIE5aJ3MgV29ybGQgQ3VwIEhvbWUgaW4gVmFuY291dmVyIHwgS2lja09kZHM='),
    'post_name'     => 'bc-place-world-cup',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/bc-place-world-cup.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[bc-place-world-cup.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QkMgUGxhY2Ug4oCUIE5aJ3MgV29ybGQgQ3VwIEhvbWUgaW4gVmFuY291dmVyIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QkMgUGxhY2Ug4oCUIE5aJ3MgV29ybGQgQ3VwIEhvbWUgaW4gVmFuY291dmVyIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QkMgUGxhY2UgaG9zdHMgdHdvIEFsbCBXaGl0ZXMgbWF0Y2hlcy4gVmVudWUgcHJvZmlsZSwgVmFuY291dmVyIGd1aWRlLCBhbmQgd2h5IHRoaXMgaXMgb3VyIGJlc3QgV29ybGQgQ3VwIGJhc2Uu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[bc-place-world-cup]=$PAGE_ID
echo "  Created 'bc-place-world-cup' (ID: $PAGE_ID)"

# --- estadio-azteca-world-cup ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('RXN0YWRpbyBBenRlY2Eg4oCUIDIwMjYgV29ybGQgQ3VwIE9wZW5pbmcgVmVudWUgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'estadio-azteca-world-cup',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/estadio-azteca-world-cup.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[estadio-azteca-world-cup.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('RXN0YWRpbyBBenRlY2Eg4oCUIDIwMjYgV29ybGQgQ3VwIE9wZW5pbmcgVmVudWUgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('RXN0YWRpbyBBenRlY2Eg4oCUIDIwMjYgV29ybGQgQ3VwIE9wZW5pbmcgVmVudWUgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RXN0YWRpbyBBenRlY2EgaG9zdHMgdGhlIG9wZW5pbmcgbWF0Y2ggb2YgdGhlIDIwMjYgV29ybGQgQ3VwLiBIaXN0b3J5LCBjaGFyYWN0ZXIsIGFuZCBNZXhpY28gQ2l0eSBndWlkZS4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[estadio-azteca-world-cup]=$PAGE_ID
echo "  Created 'estadio-azteca-world-cup' (ID: $PAGE_ID)"

# --- metlife-stadium-world-cup ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('TWV0TGlmZSBTdGFkaXVtIOKAlCBXb3JsZCBDdXAgMjAyNiBGaW5hbCBWZW51ZSB8IEtpY2tPZGRz'),
    'post_name'     => 'metlife-stadium-world-cup',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/metlife-stadium-world-cup.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[metlife-stadium-world-cup.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('TWV0TGlmZSBTdGFkaXVtIOKAlCBXb3JsZCBDdXAgMjAyNiBGaW5hbCBWZW51ZSB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('TWV0TGlmZSBTdGFkaXVtIOKAlCBXb3JsZCBDdXAgMjAyNiBGaW5hbCBWZW51ZSB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('TWV0TGlmZSBTdGFkaXVtIGhvc3RzIHRoZSAyMDI2IFdvcmxkIEN1cCBmaW5hbC4gQ2FwYWNpdHksIGNoYXJhY3RlciwgbWF0Y2hkYXkgZXhwZXJpZW5jZSwgYW5kIHZlbnVlIHJhdGluZy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[metlife-stadium-world-cup]=$PAGE_ID
echo "  Created 'metlife-stadium-world-cup' (ID: $PAGE_ID)"

# --- sofi-stadium-world-cup ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('U29GaSBTdGFkaXVtIOKAlCBBbGwgV2hpdGVzJyBXb3JsZCBDdXAgT3BlbmVyIFZlbnVlIHwgS2lja09kZHM='),
    'post_name'     => 'sofi-stadium-world-cup',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/sofi-stadium-world-cup.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[sofi-stadium-world-cup.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('U29GaSBTdGFkaXVtIOKAlCBBbGwgV2hpdGVzJyBXb3JsZCBDdXAgT3BlbmVyIFZlbnVlIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('U29GaSBTdGFkaXVtIOKAlCBBbGwgV2hpdGVzJyBXb3JsZCBDdXAgT3BlbmVyIFZlbnVlIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('U29GaSBTdGFkaXVtIGluIExBIGhvc3RzIEFsbCBXaGl0ZXMgdnMgSXJhbi4gVmVudWUgcHJvZmlsZSwgV29ybGQgQ3VwIG1hdGNoZXMsIGFuZCBLaXdpIGZhbiBndWlkZS4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[sofi-stadium-world-cup]=$PAGE_ID
echo "  Created 'sofi-stadium-world-cup' (ID: $PAGE_ID)"

# --- world-cup-2026-group-a ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQSDigJQgTWV4aWNvLCBLb3JlYSwgU0EsIEN6ZWNoaWEgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-a',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-a.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-a.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQSDigJQgTWV4aWNvLCBLb3JlYSwgU0EsIEN6ZWNoaWEgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQSDigJQgTWV4aWNvLCBLb3JlYSwgU0EsIEN6ZWNoaWEgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgQSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAuIE1leGljbyBhcyBob3N0cywgZm91ciB0ZWFtcyByYXRlZCwgcHJlZGljdGlvbnMsIGFuZCBiZXR0aW5nIGFuZ2xlcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-a]=$PAGE_ID
echo "  Created 'world-cup-2026-group-a' (ID: $PAGE_ID)"

# --- world-cup-2026-group-b ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQiDigJQgQ2FuYWRhLCBTd2l0emVybGFuZCwgUWF0YXIsIEJvc25pYSB8IEtpY2tPZGRz'),
    'post_name'     => 'world-cup-2026-group-b',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-b.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-b.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQiDigJQgQ2FuYWRhLCBTd2l0emVybGFuZCwgUWF0YXIsIEJvc25pYSB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQiDigJQgQ2FuYWRhLCBTd2l0emVybGFuZCwgUWF0YXIsIEJvc25pYSB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgQiBhbmFseXNpcy4gQ2FuYWRhIGF0IGhvbWUsIFN3aXR6ZXJsYW5kJ3MgY29uc2lzdGVuY3ksIGFuZCBiZXR0aW5nIHByZWRpY3Rpb25zIGZvciBhbGwgZm91ciB0ZWFtcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-b]=$PAGE_ID
echo "  Created 'world-cup-2026-group-b' (ID: $PAGE_ID)"

# --- world-cup-2026-group-c ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQyDigJQgQnJhemlsLCBNb3JvY2NvLCBTY290bGFuZCwgSGFpdGkgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-c',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-c.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-c.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQyDigJQgQnJhemlsLCBNb3JvY2NvLCBTY290bGFuZCwgSGFpdGkgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgQyDigJQgQnJhemlsLCBNb3JvY2NvLCBTY290bGFuZCwgSGFpdGkgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgQyBicmVha2Rvd24uIEJyYXppbCB2cyBNb3JvY2NvIGhlYWRsaW5lcywgU2NvdGxhbmQncyByZXR1cm4sIGFuZCBiZXR0aW5nIHZhbHVlIGluIHRoaXMgZ3JvdXAu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-c]=$PAGE_ID
echo "  Created 'world-cup-2026-group-c' (ID: $PAGE_ID)"

# --- world-cup-2026-group-d ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRCDigJQgVVNBLCBQYXJhZ3VheSwgQXVzdHJhbGlhLCBUdXJrZXkgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-d',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-d.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-d.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRCDigJQgVVNBLCBQYXJhZ3VheSwgQXVzdHJhbGlhLCBUdXJrZXkgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRCDigJQgVVNBLCBQYXJhZ3VheSwgQXVzdHJhbGlhLCBUdXJrZXkgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgRCBhbmFseXNpcyB3aXRoIFVTQSBhdCBob21lIGFuZCBBdXN0cmFsaWEuIFRyYW5zLVRhc21hbiBpbnRlcmVzdCwgZm91ciB0ZWFtcyByYXRlZCwgYW5kIGJldHRpbmcgcGlja3Mu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-d]=$PAGE_ID
echo "  Created 'world-cup-2026-group-d' (ID: $PAGE_ID)"

# --- world-cup-2026-group-e ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRSDigJQgR2VybWFueSwgSXZvcnkgQ29hc3QsIEVjdWFkb3IsIEN1cmHDp2FvIHwgS2lja09kZHM='),
    'post_name'     => 'world-cup-2026-group-e',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-e.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-e.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRSDigJQgR2VybWFueSwgSXZvcnkgQ29hc3QsIEVjdWFkb3IsIEN1cmHDp2FvIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRSDigJQgR2VybWFueSwgSXZvcnkgQ29hc3QsIEVjdWFkb3IsIEN1cmHDp2FvIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgRSBhbmFseXNpcy4gR2VybWFueSdzIHJlZGVtcHRpb24gcGF0aCwgSXZvcnkgQ29hc3QncyB0YWxlbnQsIGFuZCB3aGVyZSB2YWx1ZSBsaXZlcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-e]=$PAGE_ID
echo "  Created 'world-cup-2026-group-e' (ID: $PAGE_ID)"

# --- world-cup-2026-group-f ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRiDigJQgTmV0aGVybGFuZHMsIEphcGFuLCBUdW5pc2lhLCBTd2VkZW4gfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-f',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-f.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-f.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRiDigJQgTmV0aGVybGFuZHMsIEphcGFuLCBUdW5pc2lhLCBTd2VkZW4gfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRiDigJQgTmV0aGVybGFuZHMsIEphcGFuLCBUdW5pc2lhLCBTd2VkZW4gfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgRiBicmVha2Rvd24uIE5ldGhlcmxhbmRzIGFuZCBKYXBhbiBsZWFkLCBidXQgdGhpcyBncm91cCBpcyB0aWdodGVyIHRoYW4gaXQgbG9va3MuIFByZWRpY3Rpb25zIGFuZCBwaWNrcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-f]=$PAGE_ID
echo "  Created 'world-cup-2026-group-f' (ID: $PAGE_ID)"

# --- world-cup-2026-group-g ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRyDigJQgRnVsbCBBbmFseXNpcyBhbmQgUGlja3MgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-g',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-g.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-g.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRyDigJQgRnVsbCBBbmFseXNpcyBhbmQgUGlja3MgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgRyDigJQgRnVsbCBBbmFseXNpcyBhbmQgUGlja3MgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('Q29tcGxldGUgR3JvdXAgRyBhbmFseXNpcy4gQmVsZ2l1bSwgSXJhbiwgRWd5cHQsIE5ldyBaZWFsYW5kIHJhdGVkLCBzY2hlZHVsZSBpbiBOWlNULCBtYXRjaCBwcmVkaWN0aW9ucywgYW5kIGJldHRpbmcgcGlja3Mu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-g]=$PAGE_ID
echo "  Created 'world-cup-2026-group-g' (ID: $PAGE_ID)"

# --- world-cup-2026-group-h ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSCDigJQgU3BhaW4sIFVydWd1YXksIFNhdWRpLCBDYXBlIFZlcmRlIHwgS2lja09kZHM='),
    'post_name'     => 'world-cup-2026-group-h',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-h.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-h.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSCDigJQgU3BhaW4sIFVydWd1YXksIFNhdWRpLCBDYXBlIFZlcmRlIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSCDigJQgU3BhaW4sIFVydWd1YXksIFNhdWRpLCBDYXBlIFZlcmRlIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgSCBhbmFseXNpcy4gU3BhaW4gYXMgaGVhdnkgZmF2b3VyaXRlcywgVXJ1Z3VheSdzIHBlZGlncmVlLCBhbmQgYmV0dGluZyBhbmdsZXMu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-h]=$PAGE_ID
echo "  Created 'world-cup-2026-group-h' (ID: $PAGE_ID)"

# --- world-cup-2026-group-i ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSSDigJQgRnJhbmNlLCBTZW5lZ2FsLCBJcmFxLCBOb3J3YXkgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-i',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-i.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-i.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSSDigJQgRnJhbmNlLCBTZW5lZ2FsLCBJcmFxLCBOb3J3YXkgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSSDigJQgRnJhbmNlLCBTZW5lZ2FsLCBJcmFxLCBOb3J3YXkgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgSSBicmVha2Rvd24uIEZyYW5jZSBkb21pbmFudCwgU2VuZWdhbCBkYW5nZXJvdXMsIGFuZCBteSBwcmVkaWN0aW9ucyBmb3IgYWxsIG1hdGNoZXMu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-i]=$PAGE_ID
echo "  Created 'world-cup-2026-group-i' (ID: $PAGE_ID)"

# --- world-cup-2026-group-j ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSiDigJQgQXJnZW50aW5hLCBBbGdlcmlhLCBBdXN0cmlhLCBKb3JkYW4gfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-j',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-j.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-j.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSiDigJQgQXJnZW50aW5hLCBBbGdlcmlhLCBBdXN0cmlhLCBKb3JkYW4gfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSiDigJQgQXJnZW50aW5hLCBBbGdlcmlhLCBBdXN0cmlhLCBKb3JkYW4gfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgSiBhbmFseXNpcy4gRGVmZW5kaW5nIGNoYW1waW9ucyBBcmdlbnRpbmEsIEFsZ2VyaWEncyB0aHJlYXQsIGFuZCBiZXR0aW5nIHZhbHVlLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-j]=$PAGE_ID
echo "  Created 'world-cup-2026-group-j' (ID: $PAGE_ID)"

# --- world-cup-2026-group-k ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSyDigJQgUG9ydHVnYWwsIENvbG9tYmlhLCBVemJla2lzdGFuLCBEUkMgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-k',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-k.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-k.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSyDigJQgUG9ydHVnYWwsIENvbG9tYmlhLCBVemJla2lzdGFuLCBEUkMgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgSyDigJQgUG9ydHVnYWwsIENvbG9tYmlhLCBVemJla2lzdGFuLCBEUkMgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgSyBicmVha2Rvd24uIFBvcnR1Z2FsIGFuZCBDb2xvbWJpYSBmaWdodCBmb3IgdG9wIHNwb3QuIFByZWRpY3Rpb25zIGFuZCBwaWNrcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-k]=$PAGE_ID
echo "  Created 'world-cup-2026-group-k' (ID: $PAGE_ID)"

# --- world-cup-2026-group-l ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgTCDigJQgRW5nbGFuZCwgQ3JvYXRpYSwgUGFuYW1hLCBHaGFuYSB8IEtpY2tPZGRz'),
    'post_name'     => 'world-cup-2026-group-l',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-l.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-l.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgTCDigJQgRW5nbGFuZCwgQ3JvYXRpYSwgUGFuYW1hLCBHaGFuYSB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgR3JvdXAgTCDigJQgRW5nbGFuZCwgQ3JvYXRpYSwgUGFuYW1hLCBHaGFuYSB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R3JvdXAgTCBhbmFseXNpcy4gRW5nbGFuZCBhbmQgQ3JvYXRpYSByZW5ldyByaXZhbHJ5LiBGb3VyIHRlYW1zIHJhdGVkIHdpdGggYmV0dGluZyBwcmVkaWN0aW9ucy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-l]=$PAGE_ID
echo "  Created 'world-cup-2026-group-l' (ID: $PAGE_ID)"

# --- world-cup-2026-schedule-nz-times ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgU2NoZWR1bGUgaW4gTlogVGltZSDigJQgRnVsbCBUaW1ldGFibGUgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-schedule-nz-times',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-schedule-nz-times.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-schedule-nz-times.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgU2NoZWR1bGUgaW4gTlogVGltZSDigJQgRnVsbCBUaW1ldGFibGUgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgU2NoZWR1bGUgaW4gTlogVGltZSDigJQgRnVsbCBUaW1ldGFibGUgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RXZlcnkgV29ybGQgQ3VwIDIwMjYgbWF0Y2ggY29udmVydGVkIHRvIE5aU1QuIEdyb3VwIHN0YWdlLCBrbm9ja291dCByb3VuZHMsIGFuZCBBbGwgV2hpdGVzIGtpY2stb2ZmIHRpbWVzLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-schedule-nz-times]=$PAGE_ID
echo "  Created 'world-cup-2026-schedule-nz-times' (ID: $PAGE_ID)"

# --- world-cup-2026-stadiums ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgU3RhZGl1bXMg4oCUIEFsbCAxNiBWZW51ZXMgUmF0ZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-stadiums',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-stadiums.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-groups-overview]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-stadiums-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgU3RhZGl1bXMg4oCUIEFsbCAxNiBWZW51ZXMgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgU3RhZGl1bXMg4oCUIEFsbCAxNiBWZW51ZXMgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QWxsIDE2IFdvcmxkIEN1cCAyMDI2IHN0YWRpdW1zIHJhdGVkLiBVU0EsIE1leGljbywgQ2FuYWRhIHZlbnVlcyB3aXRoIE5aIHRyYXZlbCBwZXJzcGVjdGl2ZS4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-stadiums]=$PAGE_ID
echo "  Created 'world-cup-2026-stadiums' (ID: $PAGE_ID)"

# --- world-cup-2026-odds-and-predictions ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgT2RkcyBhbmQgUHJlZGljdGlvbnMg4oCUIEV4cGVydCBQaWNrcyB8IEtpY2tPZGRz'),
    'post_name'     => 'world-cup-2026-odds-and-predictions',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-odds-and-predictions.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-odds-predictions-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgT2RkcyBhbmQgUHJlZGljdGlvbnMg4oCUIEV4cGVydCBQaWNrcyB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgT2RkcyBhbmQgUHJlZGljdGlvbnMg4oCUIEV4cGVydCBQaWNrcyB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('V29ybGQgQ3VwIDIwMjYgb3V0cmlnaHQgb2RkcywgdGllciBsaXN0cywgZ29sZGVuIGJvb3QgcGlja3MsIGFuZCB2YWx1ZSBiZXRzLiBOaW5lIHllYXJzIG9mIHRvdXJuYW1lbnQgYW5hbHlzaXMgaW4gb25lIHBhZ2Uu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-odds-and-predictions]=$PAGE_ID
echo "  Created 'world-cup-2026-odds-and-predictions' (ID: $PAGE_ID)"

# --- world-cup-2026-group-g-predictions ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('R3JvdXAgRyBQcmVkaWN0aW9ucyDigJQgU2NvcmUgRm9yZWNhc3RzIGFuZCBTY2VuYXJpb3MgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-group-g-predictions',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-group-g-predictions.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-group-g-predictions-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('R3JvdXAgRyBQcmVkaWN0aW9ucyDigJQgU2NvcmUgRm9yZWNhc3RzIGFuZCBTY2VuYXJpb3MgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('R3JvdXAgRyBQcmVkaWN0aW9ucyDigJQgU2NvcmUgRm9yZWNhc3RzIGFuZCBTY2VuYXJpb3MgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RGV0YWlsZWQgR3JvdXAgRyBwcmVkaWN0aW9ucyB3aXRoIHNjb3JlIGZvcmVjYXN0cyBmb3IgYWxsIHNpeCBtYXRjaGVzLiBUaHJlZSBBbGwgV2hpdGVzIHNjZW5hcmlvcyBtb2RlbGxlZC4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-group-g-predictions]=$PAGE_ID
echo "  Created 'world-cup-2026-group-g-predictions' (ID: $PAGE_ID)"

# --- world-cup-2026-predictions ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('TXkgV29ybGQgQ3VwIDIwMjYgUHJlZGljdGlvbnMg4oCUIEZ1bGwgQnJhY2tldCB8IEtpY2tPZGRz'),
    'post_name'     => 'world-cup-2026-predictions',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-predictions.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-predictions-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('TXkgV29ybGQgQ3VwIDIwMjYgUHJlZGljdGlvbnMg4oCUIEZ1bGwgQnJhY2tldCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('TXkgV29ybGQgQ3VwIDIwMjYgUHJlZGljdGlvbnMg4oCUIEZ1bGwgQnJhY2tldCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('TXkgY29tcGxldGUgMjAyNiBXb3JsZCBDdXAgcHJlZGljdGlvbi4gRXZlcnkgZ3JvdXAgcHJlZGljdGVkLCBrbm9ja291dCBicmFja2V0IGRyYXduLCBhbmQgZmluYWwgcGljayByZXZlYWxlZC4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-predictions]=$PAGE_ID
echo "  Created 'world-cup-2026-predictions' (ID: $PAGE_ID)"

# --- world-cup-2026-quarter-finals-preview ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('d29ybGQtY3VwLTIwMjYtcXVhcnRlci1maW5hbHMtcHJldmlldw=='),
    'post_name'     => 'world-cup-2026-quarter-finals-preview',
    'post_status'   => 'draft',
    'post_content'  => '',
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_custom_seo_title', base64_decode('d29ybGQtY3VwLTIwMjYtcXVhcnRlci1maW5hbHMtcHJldmlldw=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-quarter-finals-preview]=$PAGE_ID
echo "  Created 'world-cup-2026-quarter-finals-preview' (ID: $PAGE_ID)"

# --- world-cup-2026-round-of-32-preview ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('d29ybGQtY3VwLTIwMjYtcm91bmQtb2YtMzItcHJldmlldw=='),
    'post_name'     => 'world-cup-2026-round-of-32-preview',
    'post_status'   => 'draft',
    'post_content'  => '',
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_custom_seo_title', base64_decode('d29ybGQtY3VwLTIwMjYtcm91bmQtb2YtMzItcHJldmlldw=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-round-of-32-preview]=$PAGE_ID
echo "  Created 'world-cup-2026-round-of-32-preview' (ID: $PAGE_ID)"

# --- world-cup-2026-semi-finals-and-final ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('d29ybGQtY3VwLTIwMjYtc2VtaS1maW5hbHMtYW5kLWZpbmFs'),
    'post_name'     => 'world-cup-2026-semi-finals-and-final',
    'post_status'   => 'draft',
    'post_content'  => '',
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_custom_seo_title', base64_decode('d29ybGQtY3VwLTIwMjYtc2VtaS1maW5hbHMtYW5kLWZpbmFs'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-semi-finals-and-final]=$PAGE_ID
echo "  Created 'world-cup-2026-semi-finals-and-final' (ID: $PAGE_ID)"

# --- world-cup-2026-top-scorer-odds ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgVG9wIFNjb3JlciBPZGRzIOKAlCBHb2xkZW4gQm9vdCBQaWNrcyB8IEtpY2tPZGRz'),
    'post_name'     => 'world-cup-2026-top-scorer-odds',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-top-scorer-odds.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-top-scorer-odds-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgVG9wIFNjb3JlciBPZGRzIOKAlCBHb2xkZW4gQm9vdCBQaWNrcyB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgVG9wIFNjb3JlciBPZGRzIOKAlCBHb2xkZW4gQm9vdCBQaWNrcyB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R29sZGVuIEJvb3Qgb2RkcyBmb3IgdGhlIDIwMjYgV29ybGQgQ3VwLiBGYXZvdXJpdGVzLCB2YWx1ZSBwaWNrcywgYW5kIGhvdyB0aGUgNDgtdGVhbSBmb3JtYXQgY2hhbmdlcyB0aGUgcmFjZS4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-top-scorer-odds]=$PAGE_ID
echo "  Created 'world-cup-2026-top-scorer-odds' (ID: $PAGE_ID)"

# --- world-cup-value-bets-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgVmFsdWUgQmV0cyDigJQgTWlzcHJpY2VkIE9kZHMgRm91bmQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-value-bets-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-value-bets-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-odds-and-predictions]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-value-bets-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgVmFsdWUgQmV0cyDigJQgTWlzcHJpY2VkIE9kZHMgRm91bmQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgVmFsdWUgQmV0cyDigJQgTWlzcHJpY2VkIE9kZHMgRm91bmQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('V2hlcmUgdGhlIGJvb2ttYWtlciBoYXMgaXQgd3JvbmcgYXQgdGhlIDIwMjYgV29ybGQgQ3VwLiBNeSB2YWx1ZSBiZXRzIHdpdGggY29uZmlkZW5jZSByYXRpbmdzIHBsdXMgb3ZlcnByaWNlZCBtYXJrZXRzIHRvIGF2b2lkLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-value-bets-2026]=$PAGE_ID
echo "  Created 'world-cup-value-bets-2026' (ID: $PAGE_ID)"

# --- world-cup-2026-teams ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QWxsIDQ4IFRlYW1zIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgUmF0ZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-teams',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-teams.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-teams-rated-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QWxsIDQ4IFRlYW1zIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QWxsIDQ4IFRlYW1zIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RXZlcnkgdGVhbSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAgcmF0ZWQgb24gYSAxMC1wb2ludCBzY2FsZS4gRnJvbSBjb250ZW5kZXJzIHRvIHVuZGVyZG9ncywgaW5jbHVkaW5nIHRoZSBBbGwgV2hpdGVzLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-teams]=$PAGE_ID
echo "  Created 'world-cup-2026-teams' (ID: $PAGE_ID)"

# --- all-whites-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QWxsIFdoaXRlcyBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIE5aJ3MgQ2hhbmNlcyBSYXRlZCB8IEtpY2tPZGRz'),
    'post_name'     => 'all-whites-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/all-whites-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[all-whites-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QWxsIFdoaXRlcyBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIE5aJ3MgQ2hhbmNlcyBSYXRlZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QWxsIFdoaXRlcyBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIE5aJ3MgQ2hhbmNlcyBSYXRlZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RXZlcnl0aGluZyBhYm91dCB0aGUgQWxsIFdoaXRlcyBhdCB0aGUgMjAyNiBXb3JsZCBDdXAuIEdyb3VwIEcgYW5hbHlzaXMsIENocmlzIFdvb2Qgc3BvdGxpZ2h0LCBvZGRzLCB2YWx1ZSBiZXRzLCBhbmQgbWF0Y2gtYnktbWF0Y2ggcHJldmlld3Mu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[all-whites-world-cup-2026]=$PAGE_ID
echo "  Created 'all-whites-world-cup-2026' (ID: $PAGE_ID)"

# --- all-whites-world-cup-history ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QWxsIFdoaXRlcyBXb3JsZCBDdXAgSGlzdG9yeSDigJQgMTk4MiwgMjAxMCwgYW5kIEJleW9uZCB8IEtpY2tPZGRz'),
    'post_name'     => 'all-whites-world-cup-history',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/all-whites-world-cup-history.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[all-whites-world-cup-history-hero.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QWxsIFdoaXRlcyBXb3JsZCBDdXAgSGlzdG9yeSDigJQgMTk4MiwgMjAxMCwgYW5kIEJleW9uZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QWxsIFdoaXRlcyBXb3JsZCBDdXAgSGlzdG9yeSDigJQgMTk4MiwgMjAxMCwgYW5kIEJleW9uZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('TmV3IFplYWxhbmQncyBXb3JsZCBDdXAgc3RvcnkgZnJvbSBTcGFpbiAxOTgyIHRvIFNvdXRoIEFmcmljYSAyMDEwLiBUaHJlZSBkcmF3cywgemVybyBkZWZlYXRzLCBhbmQgdGhlIHJvYWQgdG8gMjAyNi4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[all-whites-world-cup-history]=$PAGE_ID
echo "  Created 'all-whites-world-cup-history' (ID: $PAGE_ID)"

# --- argentina-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QXJnZW50aW5hIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgVGl0bGUgRGVmZW5jZSBSYXRlZCB8IEtpY2tPZGRz'),
    'post_name'     => 'argentina-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/argentina-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[argentina-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QXJnZW50aW5hIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgVGl0bGUgRGVmZW5jZSBSYXRlZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QXJnZW50aW5hIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgVGl0bGUgRGVmZW5jZSBSYXRlZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('Q2FuIEFyZ2VudGluYSBkZWZlbmQgdGhlaXIgY3Jvd24gaW4gMjAyNj8gU3F1YWQgZGVwdGgsIEdyb3VwIEogcHJldmlldywgTWVzc2kgZmFjdG9yLCBhbmQgd2hldGhlciB0aGUgb2RkcyBvZmZlciB2YWx1ZS4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[argentina-world-cup-2026]=$PAGE_ID
echo "  Created 'argentina-world-cup-2026' (ID: $PAGE_ID)"

# --- australia-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QXVzdHJhbGlhIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgU29jY2Vyb29zIFJhdGVkIHwgS2lja09kZHM='),
    'post_name'     => 'australia-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/australia-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[australia-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QXVzdHJhbGlhIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgU29jY2Vyb29zIFJhdGVkIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QXVzdHJhbGlhIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgU29jY2Vyb29zIFJhdGVkIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('VGhlIFNvY2Nlcm9vcycgMjAyNiBXb3JsZCBDdXAgY2hhbmNlcyBmcm9tIGEgS2l3aSBwZXJzcGVjdGl2ZS4gVHJhbnMtVGFzbWFuIGNvbXBhcmlzb24sIEdyb3VwIEQsIGFuZCBvZGRzLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[australia-world-cup-2026]=$PAGE_ID
echo "  Created 'australia-world-cup-2026' (ID: $PAGE_ID)"

# --- belgium-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QmVsZ2l1bSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIEdvbGRlbiBHZW5lcmF0aW9uJ3MgRW5kPyB8IEtpY2tPZGRz'),
    'post_name'     => 'belgium-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/belgium-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[belgium-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QmVsZ2l1bSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIEdvbGRlbiBHZW5lcmF0aW9uJ3MgRW5kPyB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QmVsZ2l1bSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIEdvbGRlbiBHZW5lcmF0aW9uJ3MgRW5kPyB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QmVsZ2l1bSdzIDIwMjYgV29ybGQgQ3VwIGNoYW5jZXMgYW5hbHlzZWQuIFNxdWFkIGFzc2Vzc21lbnQsIEdyb3VwIEcgb3V0bG9vaywgRGUgQnJ1eW5lIGZhY3RvciwgYW5kIG9kZHMgcmF0ZWQu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[belgium-world-cup-2026]=$PAGE_ID
echo "  Created 'belgium-world-cup-2026' (ID: $PAGE_ID)"

# --- brazil-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QnJhemlsIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgUmVidWlsZGluZyBSYXRlZCB8IEtpY2tPZGRz'),
    'post_name'     => 'brazil-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/brazil-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[brazil-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('QnJhemlsIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgUmVidWlsZGluZyBSYXRlZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QnJhemlsIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgUmVidWlsZGluZyBSYXRlZCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QnJhemlsIGluIHRyYW5zaXRpb24gaGVhZGluZyBpbnRvIDIwMjYuIFNxdWFkIGFzc2Vzc21lbnQsIEdyb3VwIEMgcHJldmlldywgYW5kIHdoZXRoZXIgdGhlIGZpdmUtdGltZSBjaGFtcGlvbnMgYXJlIG92ZXJ2YWx1ZWQu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[brazil-world-cup-2026]=$PAGE_ID
echo "  Created 'brazil-world-cup-2026' (ID: $PAGE_ID)"

# --- egypt-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('RWd5cHQgYXQgdGhlIDIwMjYgV29ybGQgQ3VwIOKAlCBTYWxhaCBhbmQgdGhlIFRocmVhdCB8IEtpY2tPZGRz'),
    'post_name'     => 'egypt-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/egypt-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[egypt-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('RWd5cHQgYXQgdGhlIDIwMjYgV29ybGQgQ3VwIOKAlCBTYWxhaCBhbmQgdGhlIFRocmVhdCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('RWd5cHQgYXQgdGhlIDIwMjYgV29ybGQgQ3VwIOKAlCBTYWxhaCBhbmQgdGhlIFRocmVhdCB8IEtpY2tPZGRz'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RWd5cHQgYXQgdGhlIDIwMjYgV29ybGQgQ3VwIGFuYWx5c2VkLiBUaGUgU2FsYWggZmFjdG9yLCBHcm91cCBHIHBvc2l0aW9uaW5nLCBhbmQgd2hhdCBpdCBtZWFucyBmb3IgQWxsIFdoaXRlcycgY2hhbmNlcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[egypt-world-cup-2026]=$PAGE_ID
echo "  Created 'egypt-world-cup-2026' (ID: $PAGE_ID)"

# --- england-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('RW5nbGFuZCBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIE5lYXJseS1NZW4gQWdhaW4/IHwgS2lja09kZHM='),
    'post_name'     => 'england-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/england-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[england-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('RW5nbGFuZCBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIE5lYXJseS1NZW4gQWdhaW4/IHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('RW5nbGFuZCBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIE5lYXJseS1NZW4gQWdhaW4/IHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RW5nbGFuZCdzIDIwMjYgV29ybGQgQ3VwIHByb3NwZWN0cyBhbmFseXNlZCBob25lc3RseS4gVGFsZW50LCB0b3VybmFtZW50IHRlbXBlcmFtZW50LCBHcm91cCBMLCBhbmQgd2hldGhlciB0aGUgb2RkcyBhcmUgZmFpci4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[england-world-cup-2026]=$PAGE_ID
echo "  Created 'england-world-cup-2026' (ID: $PAGE_ID)"

# --- france-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('RnJhbmNlIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgU3F1YWQgYW5kIE9kZHMgUmF0ZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'france-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/france-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[france-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('RnJhbmNlIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgU3F1YWQgYW5kIE9kZHMgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('RnJhbmNlIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgU3F1YWQgYW5kIE9kZHMgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('RnJhbmNlJ3MgYWJzdXJkIHNxdWFkIGRlcHRoIHJhdGVkIGZvciAyMDI2LiBHcm91cCBJIHByZXZpZXcsIE1iYXBwZSBzcG90bGlnaHQsIGFuZCBteSBwb3NpdGlvbiBvbiB0aGUgbWFya2V0Lg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[france-world-cup-2026]=$PAGE_ID
echo "  Created 'france-world-cup-2026' (ID: $PAGE_ID)"

# --- germany-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('R2VybWFueSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIFJlZGVtcHRpb24gUmF0ZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'germany-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/germany-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[germany-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('R2VybWFueSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIFJlZGVtcHRpb24gUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('R2VybWFueSBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIFJlZGVtcHRpb24gUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('R2VybWFueSdzIDIwMjYgV29ybGQgQ3VwIHByb3NwZWN0cyBhZnRlciB0aGUgaG9tZSBFdXJvLiBNdXNpYWxhLCBXaXJ0eiwgR3JvdXAgRSwgYW5kIHdoZXRoZXIgdGhlIG9kZHMgYXJlIHJpZ2h0Lg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[germany-world-cup-2026]=$PAGE_ID
echo "  Created 'germany-world-cup-2026' (ID: $PAGE_ID)"

# --- iran-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('SXJhbiBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIEdyb3VwIEcgUml2YWwgUHJvZmlsZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'iran-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/iran-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[iran-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('SXJhbiBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIEdyb3VwIEcgUml2YWwgUHJvZmlsZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('SXJhbiBhdCB0aGUgMjAyNiBXb3JsZCBDdXAg4oCUIEdyb3VwIEcgUml2YWwgUHJvZmlsZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('SXJhbidzIFdvcmxkIEN1cCAyMDI2IHByb2ZpbGUgZm9yIEtpd2kgcHVudGVycy4gU3F1YWQsIGtleSBwbGF5ZXJzLCBHcm91cCBHIHJvbGUsIGFuZCB0aGUgaGVhZC10by1oZWFkIHdpdGggQWxsIFdoaXRlcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[iran-world-cup-2026]=$PAGE_ID
echo "  Created 'iran-world-cup-2026' (ID: $PAGE_ID)"

# --- spain-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('U3BhaW4gYXQgdGhlIDIwMjYgV29ybGQgQ3VwIOKAlCBZb3VuZyBHdW5zIFJhdGVkIHwgS2lja09kZHM='),
    'post_name'     => 'spain-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/spain-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[spain-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('U3BhaW4gYXQgdGhlIDIwMjYgV29ybGQgQ3VwIOKAlCBZb3VuZyBHdW5zIFJhdGVkIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('U3BhaW4gYXQgdGhlIDIwMjYgV29ybGQgQ3VwIOKAlCBZb3VuZyBHdW5zIFJhdGVkIHwgS2lja09kZHM='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('U3BhaW4ncyBFdXJvIDIwMjQgZ2VuZXJhdGlvbiBzdGVwcyBvbnRvIHRoZSB3b3JsZCBzdGFnZS4gU3F1YWQgZGVwdGgsIFlhbWFsIHNwb3RsaWdodCwgR3JvdXAgSCwgYW5kIG9kZHMgYXNzZXNzbWVudC4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[spain-world-cup-2026]=$PAGE_ID
echo "  Created 'spain-world-cup-2026' (ID: $PAGE_ID)"

# --- usa-world-cup-2026 ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('VVNBIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgSG9tZSBBZHZhbnRhZ2UgUmF0ZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'usa-world-cup-2026',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/usa-world-cup-2026.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
    'post_parent'   => ${PAGE_IDS[world-cup-2026-teams]},
]);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[usa-world-cup-2026.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('VVNBIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgSG9tZSBBZHZhbnRhZ2UgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('VVNBIGF0IHRoZSAyMDI2IFdvcmxkIEN1cCDigJQgSG9tZSBBZHZhbnRhZ2UgUmF0ZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('VGhlIFVTTU5UIGFzIFdvcmxkIEN1cCBob3N0cy4gU3F1YWQsIEdyb3VwIEQgd2l0aCBBdXN0cmFsaWEsIGhvbWUgYWR2YW50YWdlIGZhY3RvciwgYW5kIG9kZHMgYXNzZXNzbWVudC4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[usa-world-cup-2026]=$PAGE_ID
echo "  Created 'usa-world-cup-2026' (ID: $PAGE_ID)"

# --- about-us ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('QWJvdXQgVXMgfCAkJFNJVEVfTkFNRSQk'),
    'post_name'     => 'about-us',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/about-us.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_custom_seo_title', base64_decode('QWJvdXQgVXMgfCAkJFNJVEVfTkFNRSQk'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('QWJvdXQgVXMgfCAkJFNJVEVfTkFNRSQk'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('QWJvdXQgJCRTSVRFX05BTUUkJCDigJQgYW4gaW5kZXBlbmRlbnQgV29ybGQgQ3VwIDIwMjYgYmV0dGluZyBhbmFseXNpcyBodWIuIE91ciBlZGl0b3JpYWwgbWV0aG9kb2xvZ3kgYW5kIHN0YW5kYXJkcyBleHBsYWluZWQu'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[about-us]=$PAGE_ID
echo "  Created 'about-us' (ID: $PAGE_ID)"

# --- cookie-policy ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('Q29va2llIFBvbGljeSB8ICQkU0lURV9OQU1FJCQ='),
    'post_name'     => 'cookie-policy',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/cookie-policy.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_custom_seo_title', base64_decode('Q29va2llIFBvbGljeSB8ICQkU0lURV9OQU1FJCQ='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('Q29va2llIFBvbGljeSB8ICQkU0lURV9OQU1FJCQ='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('Q29va2llIHBvbGljeSBmb3IgJCRTSVRFX05BTUUkJC4gRGV0YWlscyBvbiB3aGF0IGNvb2tpZXMgd2UgdXNlIGFuZCBob3cgdG8gbWFuYWdlIHRoZW0u'));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[cookie-policy]=$PAGE_ID
echo "  Created 'cookie-policy' (ID: $PAGE_ID)"

# --- world-cup-2026-faq ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('V29ybGQgQ3VwIDIwMjYgRkFRIOKAlCAyNSBRdWVzdGlvbnMgQW5zd2VyZWQgfCBLaWNrT2Rkcw=='),
    'post_name'     => 'world-cup-2026-faq',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/world-cup-2026-faq.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_thumbnail_id', ${MEDIA_IDS[world-cup-2026-faq.webp]});
update_post_meta(\$id, '_custom_seo_title', base64_decode('V29ybGQgQ3VwIDIwMjYgRkFRIOKAlCAyNSBRdWVzdGlvbnMgQW5zd2VyZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('V29ybGQgQ3VwIDIwMjYgRkFRIOKAlCAyNSBRdWVzdGlvbnMgQW5zd2VyZWQgfCBLaWNrT2Rkcw=='));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('MjUgY29tbW9uIHF1ZXN0aW9ucyBhYm91dCB0aGUgMjAyNiBXb3JsZCBDdXAgYW5zd2VyZWQuIEZvcm1hdCwgZ3JvdXBzLCBBbGwgV2hpdGVzLCBiZXR0aW5nLCBhbmQgTlogdmlld2luZyB0aW1lcy4='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[world-cup-2026-faq]=$PAGE_ID
echo "  Created 'world-cup-2026-faq' (ID: $PAGE_ID)"

# --- legal-notice ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('TGVnYWwgSW5mb3JtYXRpb24gfCAkJFNJVEVfTkFNRSQk'),
    'post_name'     => 'legal-notice',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/legal-notice.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_custom_seo_title', base64_decode('TGVnYWwgSW5mb3JtYXRpb24gfCAkJFNJVEVfTkFNRSQk'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('TGVnYWwgSW5mb3JtYXRpb24gfCAkJFNJVEVfTkFNRSQk'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('TGVnYWwgaW5mb3JtYXRpb24sIGRpc2NsYWltZXJzLCBhbmQgdGVybXMgb2YgdXNlIGZvciAkJFNJVEVfTkFNRSQkLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[legal-notice]=$PAGE_ID
echo "  Created 'legal-notice' (ID: $PAGE_ID)"

# --- privacy-policy ---
PAGE_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'     => 'page',
    'post_title'    => base64_decode('UHJpdmFjeSBQb2xpY3kgfCAkJFNJVEVfTkFNRSQk'),
    'post_name'     => 'privacy-policy',
    'post_status'   => 'publish',
    'post_content'  => file_get_contents('/tmp/staging/pages/privacy-policy.wp'),
    'page_template' => 'page.php',
    'post_author'   => $ADMIN_ID,
]);
wp_set_object_terms(\$id, ['Utility Pages'], 'category', false);
update_post_meta(\$id, '_custom_seo_title', base64_decode('UHJpdmFjeSBQb2xpY3kgfCAkJFNJVEVfTkFNRSQk'));
update_post_meta(\$id, '_custom_seo_headline', base64_decode('UHJpdmFjeSBQb2xpY3kgfCAkJFNJVEVfTkFNRSQk'));
update_post_meta(\$id, '_custom_seo_desc', base64_decode('UHJpdmFjeSBwb2xpY3kgZm9yICQkU0lURV9OQU1FJCQuIExlYXJuIGhvdyB3ZSBoYW5kbGUgeW91ciBkYXRhIHdoZW4geW91IHZpc2l0IG91ciB3ZWJzaXRlLg=='));
ob_end_clean();
echo \$id;
" 2>/dev/null)
PAGE_IDS[privacy-policy]=$PAGE_ID
echo "  Created 'privacy-policy' (ID: $PAGE_ID)"


# Homepage and privacy page
wp eval "
update_option('show_on_front', 'page');
update_option('page_on_front', ${PAGE_IDS[index]});
update_option('wp_page_for_privacy_policy', ${PAGE_IDS[privacy-policy]});
"

# ===========================================================================
# 9. WELCOME NEWS POST

WELCOME_POST_ID=$(wp eval "
ob_start();
\$id = wp_insert_post([
    'post_type'    => 'post',
    'post_title'   => base64_decode('V2VsY29tZSEgV2UgSGF2ZSBMYXVuY2hlZCE='),
    'post_content' => base64_decode('V2UgYXJlIHRocmlsbGVkIHRvIGFubm91bmNlIHRoZSBsYXVuY2ggb2Ygb3VyIG5ldyB3ZWJzaXRlLCDCq1NpdGUgTmFtZcK7ISBUaGlzIGlzIHRoZSBiZWdpbm5pbmcgb2Ygb3VyIGpvdXJuZXksIGFuZCB3ZSBhcmUgZXhjaXRlZCB0byBzaGFyZSBpdCB3aXRoIHlvdS4gSGVyZSB5b3Ugd2lsbCBmaW5kIHRoZSBsYXRlc3QgbmV3cywgaW50ZXJlc3RpbmcgYXJ0aWNsZXMsIGFuZCBpbXBvcnRhbnQgdXBkYXRlcy4gU3RheSB0dW5lZCBhbmQgdGhhbmsgeW91IGZvciBiZWluZyB3aXRoIHVzIQ=='),
    'post_status'  => 'publish',
    'post_author'  => $ADMIN_ID,
]);
wp_set_object_terms(\$id, 'news', 'category', false);
ob_end_clean();
echo \$id;
" 2>/dev/null)
echo "  Created welcome post (ID: $WELCOME_POST_ID)"

# ===========================================================================
# 10. MENUS

wp eval "
\$menu_id = wp_create_nav_menu('MainMenu');
\$locs = get_theme_mod('nav_menu_locations', []);
\$locs['header-menu'] = \$menu_id;
set_theme_mod('nav_menu_locations', \$locs);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[world-cup-2026-betting-guide]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish', 'menu-item-title' => base64_decode('QkVUVElORw==')]);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[world-cup-2026-groups-overview]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish', 'menu-item-title' => base64_decode('R1JPVVBT')]);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[world-cup-2026-odds-and-predictions]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish', 'menu-item-title' => base64_decode('T0REUw==')]);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[world-cup-2026-teams]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish', 'menu-item-title' => base64_decode('VEVBTVM=')]);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[world-cup-2026-faq]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish', 'menu-item-title' => base64_decode('RkFR')]);
"
echo "MainMenu created with 5 items."

wp eval "
\$menu_id = wp_create_nav_menu('FooterMenu');
\$locs = get_theme_mod('nav_menu_locations', []);
\$locs['footer-menu'] = \$menu_id;
set_theme_mod('nav_menu_locations', \$locs);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[about-us]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish']);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[cookie-policy]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish']);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[legal-notice]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish']);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[privacy-policy]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish']);
wp_update_nav_menu_item(\$menu_id, 0, ['menu-item-object-id' => ${PAGE_IDS[sitemap]}, 'menu-item-type' => 'post_type', 'menu-item-object' => 'page', 'menu-item-status' => 'publish']);
"
echo "FooterMenu created with 5 items."

# ===========================================================================
# 11. PLUGINS

wp plugin delete hello dolly
wp plugin delete akismet
echo "Default plugins removed."

# ===========================================================================
# 12. APPLICATION PASSWORD

APP_PASS=$(wp user application-password create $ADMIN_USER "autoposter" --porcelain)

echo ""
echo "========================================================="
echo "  CREDENTIALS (copy now!)"
echo "  Login:    $ADMIN_USER"
echo "  Password: $ADMIN_PASS"
echo "  Email:    $ADMIN_EMAIL"
echo "  App Pass: $APP_PASS"
echo "========================================================="
echo ""

mkdir -p wp-content/uploads
printf '{\n  "admin_user": "%s",\n  "admin_pass": "%s",\n  "admin_email": "%s",\n  "app_pass": "%s"\n}\n' \
    "$ADMIN_USER" "$ADMIN_PASS" "$ADMIN_EMAIL" "$APP_PASS" \
    > wp-content/uploads/temp_wp.json
echo "Credentials saved to wp-content/uploads/temp_wp.json"
echo "--- Done ---"
