<?php

$HELP_URLS = [
    'es' => 'https://fejar.org/',
    'fr' => 'https://www.sosjoueurs.org/',
    'de' => 'https://www.check-dein-spiel.de/',
    'pl' => 'https://www.hazardzisci.org/',
    'pt' => 'https://www.iaj.pt/',
    'nl' => 'https://openovergokken.nl/',
    'sk' => 'https://www.hratzodpovedne.sk/',
    'it' => 'https://www.issalute.it/index.php/numeri-verdi/gioco-d-azzardo',
    'et' => 'https://15410.ee/',
    'lv' => 'https://www.spelesbriviba.lv/',
    'ro' => 'https://jocresponsabil.ro/',
    'sv' => 'https://www.stodlinjen.se/',
    'lt' => 'https://nebukazartiskas.lt/',
    'bg' => 'https://nra.bg/wps/portal/nra/gambling/responsible.gambling',
    'sl' => 'https://www.zadravec.si/sl/odgovorno-igranje/',
    'hu' => 'https://sztfh.hu/tevekenysegek/szerencsejatek-felugyelet/felelos-szerencsejatek-szervezes/',
    'fi' => 'https://peluuri.fi/',
    'en' => 'https://www.begambleaware.org/',
    'cs' => 'https://www.zodpovednehrani.cz/',
    'da' => 'https://www.stopspillet.dk/',
    'ru' => 'https://www.gamblersanonymous.org/',
    'el' => 'https://www.kethea.gr/'
];

function get_site_translation($key = 'read_more')
{
    // Получаем код языка (первые 2 буквы, например 'en', 'ru')
    $lang = substr(get_bloginfo('language'), 0, 2);
    $siteName = get_bloginfo('name');

    $cookie_url = '#';
    if ($key === 'cookie_notice') {
        $page = get_page_by_path('cookie-policy');
        if ($page) {
            $cookie_url = get_permalink($page->ID);
        }
    }

    // Главный массив со всеми фразами
    $data = [
        'read_more' => [
            'es' => 'Leer más',
            'fr' => 'Lire la suite',
            'de' => 'Weiterlesen',
            'pl' => 'Czytaj więcej',
            'pt' => 'Ler mais',
            'nl' => 'Lees meer',
            'sk' => 'Čítať ďalej',
            'it' => 'Leggi tutto',
            'et' => 'Loe edasi',
            'lv' => 'Lasīt vairāk',
            'ro' => 'Citește mai mult',
            'sv' => 'Läs mer',
            'lt' => 'Skaityti daugiau',
            'bg' => 'Прочетете повече',
            'sl' => 'Preberi več',
            'hu' => 'Olvass tovább',
            'fi' => 'Lue lisää',
            'en' => 'Read more',
            'cs' => 'Číst dál',
            'da' => 'Læs mere',
            'ru' => 'Читать далее',
            'el' => 'Διαβάστε περισσότερα'
        ],
        'not_found' => [
            'es' => 'Página no encontrada',
            'fr' => 'Page non trouvée',
            'de' => 'Seite nicht gefunden',
            'pl' => 'Nie znaleziono strony',
            'pt' => 'Página não encontrada',
            'nl' => 'Pagina niet gevonden',
            'sk' => 'Stránka nebola nájdená',
            'it' => 'Pagina non trovata',
            'et' => 'Lehte ei leitud',
            'lv' => 'Lapa netika rasta',
            'ro' => 'Pagina nu a fost găsită',
            'sv' => 'Sidan hittades inte',
            'lt' => 'Puslapis nerastas',
            'bg' => 'Страницата не е намерена',
            'sl' => 'Stran ni bila najdena',
            'hu' => 'Az oldal nem található',
            'fi' => 'Sivua ei löytynyt',
            'en' => 'Page not found',
            'cs' => 'Stránka nebyla nalezena',
            'da' => 'Siden blev ikke fundet',
            'ru' => 'Страница не найдена',
            'el' => 'Η σελίδα δεν βρέθηκε'
        ],
        'toc' => [
            'es' => 'Índice de contenidos',
            'fr' => 'Table des matières',
            'de' => 'Inhaltsverzeichnis',
            'pl' => 'Spis treści',
            'pt' => 'Índice de conteúdos',
            'nl' => 'Inhoudsopgave',
            'sk' => 'Obsah',
            'it' => 'Indice dei contenuti',
            'et' => 'Sisukord',
            'lv' => 'Satura rādītājs',
            'ro' => 'Cuprins',
            'sv' => 'Innehållsförteckning',
            'lt' => 'Turinys',
            'bg' => 'Съдържание',
            'sl' => 'Kazalo vsebine',
            'hu' => 'Tartalomjegyzék',
            'fi' => 'Sisällysluettelo',
            'en' => 'Table of Contents',
            'cs' => 'Obsah',
            'da' => 'Indholdsfortegnelse',
            'ru' => 'Оглавление',
            'el' => 'Πίνακας περιεχομένων'
        ],
        'reading_time' => [
            'es' => 'Tiempo de lectura',
            'fr' => 'Temps de lecture',
            'de' => 'Lesezeit',
            'pl' => 'Czas czytania',
            'pt' => 'Tempo de leitura',
            'nl' => 'Leestijd',
            'sk' => 'Čas čítania',
            'it' => 'Tempo di lettura',
            'et' => 'Lugemisaeg',
            'lv' => 'Lasīšanas laiks',
            'ro' => 'Timp de lectură',
            'sv' => 'Lästid',
            'lt' => 'Skaitymo laikas',
            'bg' => 'Време за четене',
            'sl' => 'Čas branja',
            'hu' => 'Olvasási idő',
            'fi' => 'Lukuaika',
            'en' => 'Reading time',
            'cs' => 'Doba čtení',
            'da' => 'Læsetid',
            'ru' => 'Время чтения',
            'el' => 'Χρόνος ανάγνωσης'
        ],
        'mins' => [
            'es' => 'min',
            'fr' => 'min',
            'de' => 'Min',
            'pl' => 'min',
            'pt' => 'min',
            'nl' => 'min',
            'sk' => 'min',
            'it' => 'min',
            'et' => 'min',
            'lv' => 'min',
            'ro' => 'min',
            'sv' => 'min',
            'lt' => 'min',
            'bg' => 'мин',
            'sl' => 'min',
            'hu' => 'perc',
            'fi' => 'min',
            'en' => 'min',
            'cs' => 'min',
            'da' => 'min',
            'ru' => 'мин',
            'el' => 'λεπτά'
        ],
        'kb_bets' => [
            'es' => 'Su base de conocimientos para apuestas más inteligentes',
            'fr' => 'Votre base de connaissances pour des paris plus intelligents',
            'de' => 'Ihre Wissensdatenbank für intelligentere Wetten',
            'pl' => 'Twoja baza wiedzy dla mądrzejszych zakładów',
            'pt' => 'A sua base de conhecimentos para apostas mais inteligentes',
            'nl' => 'Uw kennisbank voor slimmere weddenschappen',
            'sk' => 'Vaša báza znalostí pre rozumnejšie stávkovanie',
            'it' => 'La tua base di conoscenza per scommesse più intelligenti',
            'et' => 'Teie teadmistebaas targemateks panusteks',
            'lv' => 'Jūsu zināšanu bāze gudrākām likmēm',
            'ro' => 'Baza ta de cunoștințe pentru pariuri mai inteligente',
            'sv' => 'Din kunskapsbas för smartare spel',
            'lt' => 'Jūsų žinių bazė protingesniems statymams',
            'bg' => 'Вашата база знания за по-умни залози',
            'sl' => 'Vaša baza znanja za pametnejše stave',
            'hu' => 'Az Ön tudásbázisa az okosabb fogadásokhoz',
            'fi' => 'Tietopankkisi älykkäämpään vedonlyöntiin',
            'en' => 'Your knowledge base for smarter bets',
            'cs' => 'Vaše znalostní báze pro chytřejší sázení',
            'da' => 'Din vidensbase for smartere væddemål',
            'ru' => 'Ваша база знаний для более разумных ставок',
            'el' => 'Η βάση γνώσεών σας για εξυπνότερα στοιχήματα'
        ],
        'legal_disclaimer' => [
            'es' => 'Esta guía es solo informativa. Por favor, juegue de forma responsable. 18+',
            'fr' => 'Ce guide est uniquement à titre informatif. Veuillez jouer de manière responsable. 18+',
            'de' => 'Dieser Leitfaden dient nur zu Informationszwecken. Bitte spielen Sie verantwortungsbewusst. 18+',
            'pl' => 'Niniejszy przewodnik ma charakter wyłącznie informacyjny. Prosimy o odpowiedzialną grę. 18+',
            'pt' => 'Este guia é apenas para fins informativos. Por favor, jogue com responsabilidade. 18+',
            'nl' => 'Deze gids is louter ter informatie. Speel verantwoordelijk. 18+',
            'sk' => 'Táto príručka slúži len na informačné účely. Hrajte zodpovedne. 18+',
            'it' => 'Questa guida è solo a scopo informativo. Si prega di giocare responsabilmente. 18+',
            'et' => 'See juhend on ainult teavitamise eesmärgil. Palun mängige vastutustundlikult. 18+',
            'lv' => 'Šī rokasgrāmata ir tikai informatīva. Lūdzu, spēlējiet atbildīgi. 18+',
            'ro' => 'Acest ghid este doar informativ. Vă rugăm să jucați responsabil. 18+',
            'sv' => 'Denna guide är endast i informationssyfte. Spela ansvarsfullt. 18+',
            'lt' => 'Šis vadovas yra tik informacinio pobūdžio. Žaiskite atsakingai. 18+',
            'bg' => 'Това ръководство е само с информационна цел. Моля, играйте отговорно. 18+',
            'sl' => 'Ta priročnik je zgolj informativne narave. Igrajte odgovorno. 18+',
            'hu' => 'Ez az útmutató kizárólag tájékoztató jellegű. Kérjük, játsszon felelősségteljesen. 18+',
            'fi' => 'Tämä opas on vain tiedotuskäyttöön. Pelaa vastuullisesti. 18+',
            'en' => 'This guide is for informational purposes only. Please play responsibly. 18+',
            'cs' => 'Tato příručka slouží pouze pro informační účely. Hrajte prosím zodpovědnie. 18+',
            'da' => 'Denne guide er kun til informationsformål. Spil venligst ansvarligt. 18+',
            'ru' => 'Данное руководство носит исключительно информационный характер. Пожалуйста, играйте ответственно. 18+',
            'el' => 'Αυτός ο οδηγός είναι μόνο για ενημερωτικούς σκοπούς. Παρακαλούμε παίξτε υπεύθυνα. 18+'
        ],
        'cookie_notice' => [
            'es' => 'Utilizamos cookies para mejorar su experiencia. Al continuar en el sitio, acepta <a href="' . $cookie_url . '">nuestra política</a>.',
            'fr' => 'Nous utilisons des cookies pour améliorer votre expérience. En restant sur le site, vous acceptez <a href="' . $cookie_url . '">notre politique</a>.',
            'de' => 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern. Durch die weitere Nutzung der Website stimmen Sie <a href="' . $cookie_url . '">unserer Richtlinie</a> zu.',
            'pl' => 'Używamy plików cookie, aby poprawić Twój komfort korzystania z witryny. Pozostając na stronie, wyrażasz zgodę na <a href="' . $cookie_url . '">naszą politykę</a>.',
            'pt' => 'Utilizamos cookies para melhorar a sua experiência. Ao continuar no site, concorda com a <a href="' . $cookie_url . '">nossa política</a>.',
            'nl' => 'Wij gebruiken cookies om uw ervaring te verbeteren. Door op de site te blijven, gaat u akkoord met <a href="' . $cookie_url . '">ons beleid</a>.',
            'sk' => 'Používame súbory cookie, aby sme zlepšili váš zážitok. Zotrvaním na stránke súhlasíte s <a href="' . $cookie_url . '">našimi pravidlami</a>.',
            'it' => 'Utilizzamo i cookie per migliorare la tua esperienza. Rimanendo sul sito, accetti la <a href="' . $cookie_url . '">nostra politica</a>.',
            'et' => 'Kasutame küpsiseid teie kogemuse parandamiseks. Saidile jäädes nõustute <a href="' . $cookie_url . '">meie poliitikaga</a>.',
            'lv' => 'Mēs izmantojam sīkfailus, lai uzlabotu jūsu lietošanas pieredzi. Paliekot vietnē, jūs piekrītat <a href="' . $cookie_url . '">mūsu politikai</a>.',
            'ro' => 'Folosim cookie-uri pentru a vă îmbunătăți experiența. Prin continuarea pe site, sunteți de acord cu <a href="' . $cookie_url . '">politica noastră</a>.',
            'sv' => 'Vi använder cookies för att förbättra din upplevelse. Genom att stanna på sidan godkänner du <a href="' . $cookie_url . '">vår policy</a>.',
            'lt' => 'Naudojame slapukus jūsų patirčiai pagerinti. Likdami svetainėje sutinkate su <a href="' . $cookie_url . '">mūsų politika</a>.',
            'bg' => 'Използваме бисквитки, за да подобрим вашето преживяване. Престоят на сайта означава, че приемате <a href="' . $cookie_url . '">нашата политика</a>.',
            'sl' => 'Uporabljamo piškotke za izboljšanje vaše izkušnje. Z ostankom na strani se strinjate z <a href="' . $cookie_url . '">našo politiko</a>.',
            'hu' => 'Sütiket használunk a felhasználói élmény javítása érdekében. A weboldalon való tartózkodással elfogadja <a href="' . $cookie_url . '">szabályzatunkat</a>.',
            'fi' => 'Käytämme evästeitä parantaaksemme käyttökokemustasi. Jäämällä sivustolle hyväksyt <a href="' . $cookie_url . '">käytäntömme</a>.',
            'en' => 'We use cookies to improve your experience. By staying on the site, you agree to <a href="' . $cookie_url . '">our policy</a>.',
            'cs' => 'Používáme soubory cookie ke zlepšení vašeho zážitku. Setrváním na stránce souhlasíte s <a href="' . $cookie_url . '">našimi zásadami</a>.',
            'da' => 'Vi bruger cookies til at forbedre din oplevelse. Ved at blive på siden accepterer du <a href="' . $cookie_url . '">vores politik</a>.',
            'ru' => 'Мы используем cookie для улучшения вашего опыта. Оставаясь на сайте, вы соглашаетесь с <a href="' . $cookie_url . '">нашей политикой</a>.',
            'el' => 'Χρησιμοποιούμε cookies για να βελτιώσουμε την εμπειρία σας. Παραμένοντας στον ιστότοπο, αποδέχεστε την <a href="' . $cookie_url . '">πολιτική μας</a>.'
        ],
        'cookie_notice_modal' => [
            'es' => 'Utilizamos cookies para mejorar su experiencia, analizar el tráfico y personalizar anuncios. Por favor, acepte o configure sus preferencias.',
            'fr' => 'Nous utilisons des cookies pour améliorer votre expérience, analyser le trafic et personnaliser les publicités. Veuillez accepter ou paramétrer vos préférences.',
            'de' => 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern, den Datenverkehr zu analysieren und Anzeigen zu personalisieren. Bitte akzeptieren Sie diese oder passen Sie Ihre Einstellungen an.',
            'pl' => 'Używamy plików cookie, aby poprawić komfort użytkowania, analizować ruch i personalizować reklamy. Prosimy o zaakceptowanie lub skonfigurowanie preferencji.',
            'pt' => 'Utilizamos cookies para melhorar a sua experiência, analisar o tráfego e personalizar anúncios. Por favor, aceite ou configure as suas preferências.',
            'nl' => 'Wij gebruiken cookies om uw ervaring te verbeteren, verkeer te analyseren en advertenties te personalisieren. Accepteer deze of stel uw voorkeuren in.',
            'sk' => 'Súbory cookie používame na zlepšenie vášho zážitku, analýzu návštevnosti a personalizáciu reklám. Prijmite ich alebo upravte svoje nastavenia.',
            'it' => 'Utilizziamo i cookie per migliorare la tua esperienza, analizzare il traffico e personalizzare gli annunci. Accetta o personalizza le tue preferenze.',
            'et' => 'Kasutame küpsiseid teie kogemuse parandamiseks, liikluse analüüsimiseks ja reklaamide isikupärastamiseks. Palun nõustuge või seadistage oma eelistused.',
            'lv' => 'Mēs izmantojame sīkfailus, lai uzlabotu jūsu pieredzi, analizētu trafiku un personalizētu reklāmas. Lūdzu, apstipriniet vai iestatiet savas preferences.',
            'ro' => 'Folosim cookie-uri pentru a vă îmbunătăți experiența, pentru a analiza traficul și pentru a personaliza reclamele. Vă rugăm să acceptați sau să vă configurați preferințele.',
            'sv' => 'Vi använder cookies för att förbättra din upplevelse, analysera trafik och anpassa annonser. Godkänn eller ställ in dina preferenser.',
            'lt' => 'Naudojame slapukus, kad pagerintume jūsų patirtį, analizuotume srautą ir pritaikytume skelbimus. Sutikite arba nustatykite savo pasirinkimus.',
            'bg' => 'Използваме бисквитки за подобряване на преживяването, анализ на трафика и персонализиране на реклами. Моля, приемете или настройте предпочитанията си.',
            'sl' => 'Piškotke uporabljamo za izboljšanie vaše izkušnje, analizo prometa in prilagajanje oglasov. Prosimo, sprejmite jih ali uredite svoje nastavitve.',
            'hu' => 'Sütiket használunk a felhasználói élmény javítása, a forgalom elemzése és a hirdetések személyre szabása érdekében. Kérjük, fogadja el őket, vagy állítsa be preferenciáit.',
            'fi' => 'Käytämme evästeitä parantaaksemme kokemustasi, analysoidaksemme liikennettä ja personoidaksemme mainoksia. Hyväksy tai muokkaa asetuksiasi.',
            'en' => 'We use cookies to enhance your experience, analyze traffic, and personalize ads. Please accept or manage your preferences.',
            'cs' => 'Používáme soubory cookie ke zlepšení vašeho zážitku, analýze návštevnosti a personalizaci reklam. Přijměte je nebo upravte své nastavení.',
            'da' => 'Vi bruger cookies til at forbedre din oplevelse, analysere trafik og tilpasse annoncer. Accepter venligst eller administrer dine præferencer.',
            'ru' => 'Мы используем куки для улучшения вашего опыта, анализа трафика и персонализации рекламы. Пожалуйста, примите их или настройте свои предпочтения.',
            'el' => 'Χρησιμοποιούμε cookies για να βελτιώσουμε την εμπειρία σας, να αναλύσουμε την κίνηση και να εξατομικεύσουμε τις διαφημίσεις. Παρακαλούμε αποδεχτείτε ή ρυθμίστε τις προτιμήσεις σας.'
        ],
        'expert_checked' => [
            'es' => 'Verificado por un experto',
            'fr' => 'Vérifié par un expert',
            'de' => 'Von Experten geprüft',
            'pl' => 'Zweryfikowane przez eksperta',
            'pt' => 'Verificado por um especialista',
            'nl' => 'Geverifieerd door een expert',
            'sk' => 'Overené odborníkom',
            'it' => 'Verificato da un esperto',
            'et' => 'Eksperdi poolt kontrollitud',
            'lv' => 'Eksperta pārbaudīts',
            'ro' => 'Verificat de un expert',
            'sv' => 'Granskad av en expert',
            'lt' => 'Patikrinta eksperto',
            'bg' => 'Проверено от експерт',
            'sl' => 'Preveril strokovnjak',
            'hu' => 'Szakértő által ellenőrizve',
            'fi' => 'Asiantuntijan tarkistama',
            'en' => 'Expertly verified',
            'cs' => 'Ověřeno odborníkem',
            'da' => 'Verificeret af en ekspert',
            'ru' => 'Проверено экспертом',
            'el' => 'Επαληθεύτηκε από ειδικό'
        ],
        'affiliate_disclosure' => [
            'es' => 'Este sitio contiene enlaces de afiliados. Podemos recibir una comisión si realiza una compra a través de ellos, sin costo adicional para usted.',
            'fr' => 'Ce site contient des liens d\'affiliation. Nous pouvons recevoir une commission si vous passez par ces liens, sans coût supplémentaire pour vous.',
            'de' => 'Diese Website enthält Affiliate-Links. Wir erhalten möglicherweise eine Provision, wenn Sie über diese Links einkaufen, ohne dass Ihnen zusätzliche Kosten entstehen.',
            'pl' => 'Ta strona zawiera linki partnerskie. Możemy otrzymać prowizję, jeśli skorzystasz z tych linków, bez żadnych dodatkowych kosztów dla Ciebie.',
            'pt' => 'Este site contém links de afiliados. Podemos receber uma comissão se fizer uma compra através deles, sem qualquer custo adicional para si.',
            'nl' => 'Deze site bevat affiliate links. We kunnen een commissie ontvangen als u via deze links een aankoop doet, zonder extra kosten voor u.',
            'sk' => 'Táto stránka obsahuje partnerské odkazy. Ak cez ne nakúpite, môžeme dostať províziu bez akýchkoľvek ďalších nákladov pre vás.',
            'it' => 'Questo sito contiene link di affiliazione. Potremmo ricevere una commissione se effettui un acquisto tramite questi link, senza alcun costo aggiuntivo per te.',
            'et' => 'See sait sisaldab partnerlinke. Me võime saada vahendustasu, kui teete ostu nende kaudu, ilma teile lisakuludeta.',
            'lv' => 'Šī vietne satur partneru saites. Mēs varam saņemt komisijas maksu, ja veicat pirkumu caur tām, bez papildu izmaksām jums.',
            'ro' => 'Acest site conține linkuri de afiliere. Putem primi un comision dacă faceți o achiziție prin acestea, fără niciun cost suplimentar pentru dvs.',
            'sv' => 'Denna sida innehåller affiliatelänkar. Vi kan få en provision om du genomför ett köp via dessa länkar, utan extra kostnad för dig.',
            'lt' => 'Šioje svetainėje yra partnerių nuorodų. Galime gauti komisinių, jei pirksite per jas, be jokių papildomų išlaidų jums.',
            'bg' => 'Този сайт съдържа партньорски връзки. Може да получим комисионна, ако направите покупка чрез тях, без допълнителни разходи за вас.',
            'sl' => 'To spletno mesto vsebuje partnerske povezave. Če opravite nakup prek njih, lahko prejmemo provizijo brez kakršnih koli dodatnih stroškov za vas.',
            'hu' => 'Ez az oldal partnerlinkeket tartalmaz. Jutalékot kaphatunk, ha ezeken keresztül vásárol, anélkül, hogy ez Önnek plusz költségbe kerülne.',
            'fi' => 'Tämä sivusto sisältää kumppanuuslinkkejä. Saatamme saada komission, jos teet ostoksen niiden kautta, ilman lisäkustannuksia sinulle.',
            'en' => 'This site contains affiliate links. We may receive a commission if you make a purchase through them, at no additional cost to you.',
            'cs' => 'Tato stránka obsahuje partnerské odkazy. Pokud přes ně nakoupíte, můžeme obdržet provizi bez jakýchkoli dodatečných nákladů pro vás.',
            'da' => 'Denne side indeholder affiliatelinks. Vi kan modtage en kommission, hvis du foretager et køb via disse links, uden ekstra omkostninger for dig.',
            'ru' => 'Этот сайт содержит партнерские ссылки. Мы можем получать комиссию, если вы перейдете по ним, без дополнительных затрат для вас.',
            'el' => 'Αυτός ο ιστότοπος περιέχει συνδέσμους συνεργατών. Ενδέχεται να λάβουμε προμήθεια εάν πραγματοποιήσετε μια αγορά μέσω αυτών, χωρίς επιπλέον κόστος για εσάς.'
        ],
        'help_text' => [
            'es' => 'Si tiene problemas con el juego, puede encontrar ayuda aquí',
            'fr' => 'Si vous avez un problème de dépendance au jeu, vous pouvez trouver de l\'aide ici',
            'de' => 'Wenn Sie unter Spielsucht leiden, finden Sie hier Hilfe',
            'pl' => 'Jeśli masz problem z uzależnieniem od hazardu, tutaj możesz uzyskać pomoc',
            'pt' => 'Se tem problemas com o vício do jogo, pode encontrar ajuda aqui',
            'nl' => 'Als u kampt met een gokverslaving, kunt u hier hulp vinden',
            'sk' => 'Ak máte problémy s hazardným hraním, pomoc nájdete tu',
            'it' => 'Se hai problemi di dipendenza dal gioco, puoi trovare aiuto qui',
            'et' => 'Kui teil on probleeme hasartmängusõltuvusega, leiate abi siit',
            'lv' => 'Ja jums ir problēmas ar azartspēļu atkarību, palīdzību varat atrast šeit',
            'ro' => 'Dacă te confrunți cu dependența de jocuri de noroc, poți găsi ajutor aici',
            'sv' => 'Om du har problem med spelberoende kan du få hjälp här',
            'lt' => 'Jei turite problemų dėl priklausomybės nuo lošimų, pagalbos galite kreiptis čia',
            'bg' => 'Ако имате проблем с хазартна зависимост, можете да намерите помощ тук',
            'sl' => 'Če imate težave z odvisnostjo od iger na srečo, lahko pomoč poiščete tukaj',
            'hu' => 'Ha szerencsejáték-függőséggel küzd, itt segítséget kaphat',
            'fi' => 'Jos kärsit peliriippuvuudesta, löydät apua täältä',
            'en' => 'If you are struggling with gambling addiction, you can find help here',
            'cs' => 'Pokud bojujete se závislostí na hazardních hrách, pomoc najdete zde',
            'da' => 'Hvis du kæmper med ludomani, kan du finde hjælp her',
            'ru' => 'Если вы столкнулись с игровой зависимостью, вы можете получить помощь здесь',
            'el' => 'Εάν αντιμετωπίζετε πρόβλημα εθισμού στον τζόγο, μπορείτε να βρείτε βοήθεια εδώ'
        ],
        '404_title' => [
            'es' => 'Página no encontrada',
            'fr' => 'Page non trouvée',
            'de' => 'Seite nicht gefunden',
            'pl' => 'Nie znaleziono strony',
            'pt' => 'Página não encontrada',
            'nl' => 'Pagina niet gevonden',
            'sk' => 'Stránka nebola nájdená',
            'it' => 'Pagina non trovata',
            'et' => 'Lehte ei leitud',
            'lv' => 'Lapa netika rasta',
            'ro' => 'Pagina nu a fost găsită',
            'sv' => 'Sidan hittades inte',
            'lt' => 'Puslapis nerastas',
            'bg' => 'Страницата не е намерена',
            'sl' => 'Stran ni bila najdena',
            'hu' => 'Az oldal nem található',
            'fi' => 'Sivua ei löytynyt',
            'en' => 'Page not found',
            'cs' => 'Stránka nebyla nalezena',
            'da' => 'Siden blev ikke fundet',
            'ru' => 'Страница не найдена',
            'el' => 'Η σελίδα δεν βρέθηκε'
        ],
        '404_description' => [
            'es' => 'Lo sentimos, la página solicitada ya no existe o ha sido movida.',
            'fr' => 'Désolé, la page demandée n\'existe plus ou a été déplacée.',
            'de' => 'Entschuldigung, die angeforderte Seite existiert nicht mehr oder wurde verschoben.',
            'pl' => 'Przepraszamy, żądana strona już nie istnieje lub została przeniesiona.',
            'pt' => 'Desculpe, a página solicitada já não existe ou foi movida.',
            'nl' => 'Sorry, de opgevraagde pagina bestaat niet meer of is verplaatst.',
            'sk' => 'Ľutujeme, požadovaná stránka už neexistuje alebo bola presunutá.',
            'it' => 'Spiacenti, la pagina richiesta non esiste più o è stata spostata.',
            'et' => 'Vabandust, soovitud lehte pole enam olemas või see on teisaldatud.',
            'lv' => 'Atvainojiet, pieprasītā lapa vairs neeksistē vai ir pārvietota.',
            'ro' => 'Ne pare rău, pagina solicitată nu mai există sau a fost mutată.',
            'sv' => 'Tyvärr, den begärda sidan finns inte längre eller har flyttats.',
            'lt' => 'Apgailestaujame, pageidaujamas puslapis nebeegzistuoja arba buvo perkeltas.',
            'bg' => 'Съжаляваме, поисканата страница вече не съществува или е преместена.',
            'sl' => 'Oprostite, zahtevana stran ne obstaja več ali pa je bila premaknjena.',
            'hu' => 'Sajnáljuk, a kért oldal már nem létezik, vagy áthelyezték.',
            'fi' => 'Valitettavasti pyydettyä sivua ei ole enää olemassa või se on siirretty.',
            'en' => 'Sorry, the requested page no longer exists or has been moved.',
            'cs' => 'Omlouváme se, požadovaná stránka již neexistuje nebo byla přesunuta.',
            'da' => 'Beklager, den ønskede side eksisterer ikke længere eller er blevet flyttet.',
            'ru' => 'Извините, запрашиваемая страница больше не существует или была перемещена.',
            'el' => 'Λυπούμαστε, η σελίδα που ζητήσατε δεν υπάρχει πλέον ή έχει μετακινηθεί.'
        ],
        '404_back_home' => [
            'es' => 'Volver al inicio',
            'fr' => 'Retour à l\'accueil',
            'de' => 'Zurück zur Startseite',
            'pl' => 'Wróć do strony głównej',
            'pt' => 'Voltar ao início',
            'nl' => 'Terug naar home',
            'sk' => 'Späť na hlavnú stránku',
            'it' => 'Torna alla home',
            'et' => 'Tagasi avalehele',
            'lv' => 'Atpakaļ uz sākumu',
            'ro' => 'Înapoi la prima pagină',
            'sv' => 'Tillbaka till start',
            'lt' => 'Grįžti į pagrindinį',
            'bg' => 'Обратно към началото',
            'sl' => 'Nazaj na domovino',
            'hu' => 'Vissza a főoldalra',
            'fi' => 'Takaisin etusivulle',
            'en' => 'Back to home',
            'cs' => 'Zpět na hlavní stranu',
            'da' => 'Tilbage til forsiden',
            'ru' => 'Вернуться на главную',
            'el' => 'Επιστροφή στην αρχική'
        ],
        '404_go_to_kb' => [
            'es' => 'Ir a la base de conocimientos',
            'fr' => 'Aller à la base de connaissances',
            'de' => 'Zur Wissensdatenbank',
            'pl' => 'Przejdź do bazy wiedzy',
            'pt' => 'Ir para a base de conhecimentos',
            'nl' => 'Ga naar de kennisbank',
            'sk' => 'Prejsť do bázy znalostí',
            'it' => 'Vai alla base di conoscenza',
            'et' => 'Mine teadmistebaasi',
            'lv' => 'Doties uz zināšanu bāzi',
            'ro' => 'Mergi la baza de cunoștințe',
            'sv' => 'Gå till kunskapsbasen',
            'lt' => 'Eiti į žinių bazę',
            'bg' => 'Към базата знания',
            'sl' => 'Pojdi v bazo znanja',
            'hu' => 'Ugrás a tudásbázishoz',
            'fi' => 'Siirry tietopankkiin',
            'en' => 'Go to knowledge base',
            'cs' => 'Přejít do znalostní báze',
            'da' => 'Gå til vidensbase',
            'ru' => 'Перейти в базу знаний',
            'el' => 'Μετάβαση στη βάση γνώσεων'
        ],
        'accept_all' => [
            'es' => 'Aceptar todo',
            'fr' => 'Tout accepter',
            'de' => 'Alle akzeptieren',
            'pl' => 'Akceptuj wszystko',
            'pt' => 'Aceitar todos',
            'nl' => 'Alles accepteren',
            'sk' => 'Prijať všetko',
            'it' => 'Accetta tutto',
            'et' => 'Nõustun kõigega',
            'lv' => 'Apstiprināt visu',
            'ro' => 'Acceptă tot',
            'sv' => 'Acceptera alla',
            'lt' => 'Sutikti su visais',
            'bg' => 'Приеми всички',
            'sl' => 'Sprejmi vse',
            'hu' => 'Összes elfogadása',
            'fi' => 'Hyväksy kaikki',
            'en' => 'Accept all',
            'cs' => 'Přijmout vše',
            'da' => 'Accepter alle',
            'ru' => 'Принять всё',
            'el' => 'Αποδοχή όλων'
        ],
        'reject_all' => [
            'es' => 'Rechazar todo',
            'fr' => 'Tout refuser',
            'de' => 'Alle ablehnen',
            'pl' => 'Odrzuć wszystko',
            'pt' => 'Rejeitar todos',
            'nl' => 'Alles weigeren',
            'sk' => 'Odmietnuť všetko',
            'it' => 'Rifiuta tutto',
            'et' => 'Keeldu kõigest',
            'lv' => 'Noraidīt visu',
            'ro' => 'Refuză tot',
            'sv' => 'Neka alla',
            'lt' => 'Atmesti visus',
            'bg' => 'Откажи всички',
            'sl' => 'Zavrni vse',
            'hu' => 'Összes elutasítása',
            'fi' => 'Hylkää kaikki',
            'en' => 'Reject all',
            'cs' => 'Odmítnout vše',
            'da' => 'Afvis alle',
            'ru' => 'Отклонить всё',
            'el' => 'Απόρριψη όλων'
        ],
        'settings' => [
            'es' => 'Configurar',
            'fr' => 'Paramétrer',
            'de' => 'Einstellungen',
            'pl' => 'Ustawienia',
            'pt' => 'Definições',
            'nl' => 'Instellingen',
            'sk' => 'Nastavenia',
            'it' => 'Impostazioni',
            'et' => 'Seaded',
            'lv' => 'Iestatījumi',
            'ro' => 'Setări',
            'sv' => 'Inställningar',
            'lt' => 'Nustatymai',
            'bg' => 'Настройки',
            'sl' => 'Nastavitve',
            'hu' => 'Beállítások',
            'fi' => 'Asetukset',
            'en' => 'Settings',
            'cs' => 'Nastavení',
            'da' => 'Indstillinger',
            'ru' => 'Настройки',
            'el' => 'Ρυθμίσεις'
        ],
        'privacy_policy' => [
            'es' => 'Política de privacidad',
            'fr' => 'Politique de confidentialité',
            'de' => 'Datenschutzerklärung',
            'pl' => 'Polityka prywatności',
            'pt' => 'Política de privacidade',
            'nl' => 'Privacybeleid',
            'sk' => 'Zásady ochrany súkromia',
            'it' => 'Informativa sulla privacy',
            'et' => 'Privaatsuspoliitika',
            'lv' => 'Privātuma politika',
            'ro' => 'Politică de confidențialitate',
            'sv' => 'Integritetspolicy',
            'lt' => 'Privatumo politika',
            'bg' => 'Политика за поверителност',
            'sl' => 'Pravilnik o zasebnosti',
            'hu' => 'Adatvédelmi irányelvek',
            'fi' => 'Tietosuojaseloste',
            'en' => 'Privacy Policy',
            'cs' => 'Zásady ochrany soukromí',
            'da' => 'Privatlivspolitik',
            'ru' => 'Политика конфиденциальности',
            'el' => 'Πολιτική Απορρήτου'
        ],
        'cookie_policy' => [
            'es' => 'Política de cookies',
            'fr' => 'Politique relative aux cookies',
            'de' => 'Cookie-Richtlinie',
            'pl' => 'Polityka cookies',
            'pt' => 'Política de cookies',
            'nl' => 'Cookiebeleid',
            'sk' => 'Zásady používania súborov cookie',
            'it' => 'Informativa sui cookie',
            'et' => 'Küpsiste poliitika',
            'lv' => 'Sīkdatņu politika',
            'ro' => 'Politică de cookie-uri',
            'sv' => 'Cookiepolicy',
            'lt' => 'Slapukų politika',
            'bg' => 'Политика за бисквитките',
            'sl' => 'Pravilnik o piškotkih',
            'hu' => 'Süti irányelvek',
            'fi' => 'Evästekäytäntö',
            'en' => 'Cookie Policy',
            'cs' => 'Zásady používání cookies',
            'da' => 'Cookiepolitik',
            'ru' => 'Политика использования куки',
            'el' => 'Πολιτική Cookies'
        ],
        'information' => [
            'es' => 'Información',
            'fr' => 'Information',
            'de' => 'Informationen',
            'pl' => 'Informacja',
            'pt' => 'Informação',
            'nl' => 'Informatie',
            'sk' => 'Informácie',
            'it' => 'Informazioni',
            'et' => 'Teave',
            'lv' => 'Informācija',
            'ro' => 'Informație',
            'sv' => 'Information',
            'lt' => 'Informacija',
            'bg' => 'Информация',
            'sl' => 'Informacije',
            'hu' => 'Információ',
            'fi' => 'Tiedot',
            'en' => 'Information',
            'cs' => 'Informace',
            'da' => 'Information',
            'ru' => 'Информация',
            'el' => 'Πληροφορίες'
        ],
        'disclaimer' => [
            'es' => 'Aviso legal',
            'fr' => 'Clause de non-responsabilité',
            'de' => 'Haftungsausschluss',
            'pl' => 'Zastrzeżenie',
            'pt' => 'Aviso legal',
            'nl' => 'Disclaimer',
            'sk' => 'Vyhlásenie o zodpovednosti',
            'it' => 'Esclusione di responsabilità',
            'et' => 'Vastutuse välistamine',
            'lv' => 'Atruna',
            'ro' => 'Clauză de declinare a responsabilității',
            'sv' => 'Ansvarsfriskrivning',
            'lt' => 'Atsakomybės apribojimas',
            'bg' => 'Отказ от отговорност',
            'sl' => 'Zavrnitev odgovornosti',
            'hu' => 'Jogi nyilatkozat',
            'fi' => 'Vastuuvapauslauseke',
            'en' => 'Disclaimer',
            'cs' => 'Vyloučení odpovědnosti',
            'da' => 'Ansvarsfraskrivelse',
            'ru' => 'Отказ от ответственности',
            'el' => 'Αποποίηση ευθυνών'
        ],
        'related_articles' => [
            'es' => 'Artículos relacionados',
            'fr' => 'Articles connexes',
            'de' => 'Ähnliche Artikel',
            'pl' => 'Powiązane artykuły',
            'pt' => 'Artigos relacionados',
            'nl' => 'Gerelateerde artikelen',
            'sk' => 'Súvisiace články',
            'it' => 'Articoli correlati',
            'et' => 'Seotud artiklid',
            'lv' => 'Saistītie raksti',
            'ro' => 'Articole similare',
            'sv' => 'Relaterade artiklar',
            'lt' => 'Susiję straipsniai',
            'bg' => 'Подобни статии',
            'sl' => 'Sorodni članki',
            'hu' => 'Kapcsolódó cikkek',
            'fi' => 'Aiheeseen liittyvät artikkelit',
            'en' => 'Related articles',
            'cs' => 'Související články',
            'da' => 'Relaterede artikler',
            'ru' => 'Статьи по теме',
            'el' => 'Σχετικά άρθρα'
        ],
        'pages' => [
            'es' => 'Páginas',
            'fr' => 'Pages',
            'de' => 'Seiten',
            'pl' => 'Strony',
            'pt' => 'Páginas',
            'nl' => 'Pagina\'s',
            'sk' => 'Stránky',
            'it' => 'Pagine',
            'et' => 'Leheküljed',
            'lv' => 'Lapas',
            'ro' => 'Pagini',
            'sv' => 'Sidor',
            'lt' => 'Puslapiai',
            'bg' => 'Страници',
            'sl' => 'Strani',
            'hu' => 'Oldalak',
            'fi' => 'Sivut',
            'en' => 'Pages',
            'cs' => 'Stránky',
            'da' => 'Sider',
            'ru' => 'Страницы',
            'el' => 'Σελίδες'
        ],
        'home' => [
            'es' => 'Inicio',
            'fr' => 'Accueil',
            'de' => 'Startseite',
            'pl' => 'Strona główna',
            'pt' => 'Início',
            'nl' => 'Home',
            'sk' => 'Domov',
            'it' => 'Home',
            'et' => 'Avaleht',
            'lv' => 'Sākums',
            'ro' => 'Acasă',
            'sv' => 'Hem',
            'lt' => 'Pradžia',
            'bg' => 'Начало',
            'sl' => 'Domov',
            'hu' => 'Főoldal',
            'fi' => 'Koti',
            'en' => 'Home',
            'cs' => 'Domů',
            'da' => 'Hjem',
            'ru' => 'Главная',
            'el' => 'Αρχική'
        ],
        'sitemap-description' => [
            'es' => "Mapa del sitio $siteName: lista completa de secciones y páginas.",
            'fr' => "Plan du site $siteName : liste complète des sections et des pages.",
            'de' => "Sitemap $siteName: Vollständige Liste der Bereiche und Seiten.",
            'pl' => "Mapa strony $siteName: pełna lista sekcji i stron.",
            'pt' => "Mapa do site $siteName: lista completa de seções e páginas.",
            'nl' => "Sitemap $siteName: volledige lijst van secties en pagina's.",
            'sk' => "Mapa stránok $siteName: úplný zoznam sekcií a stránok.",
            'it' => "Mappa del sito $siteName: elenco completo di sezioni e pagine.",
            'et' => "Saidikaart $siteName: täielik jaotiste ja lehtede loend.",
            'lv' => "Vietnes karte $siteName: pilns sadaļu un lapu saraksts.",
            'ro' => "Harta site-ului $siteName: lista completă de secțiuni și pagini.",
            'sv' => "Webbplatskarta $siteName: fullständig lista över sektioner och sidor.",
            'lt' => "Svetainės medis $siteName: pilnas skiltių ir puslapių sąrašas.",
            'bg' => "Карта на сайта $siteName: пълен списък на раздели и страници.",
            'sl' => "Zemljevid spletnega mesta $siteName: celoten seznam razdelkov in strani.",
            'hu' => "Oldaltérkép $siteName: a szakaszok és oldalak teljes listája.",
            'fi' => "Sivukartta $siteName: täydellinen luettelo osioista ja sivuista.",
            'en' => "Sitemap $siteName: full list of sections and pages.",
            'cs' => "Mapa stránek $siteName: úplný seznam sekcí a stránek.",
            'da' => "Sitemap $siteName: komplet liste over sektioner og sider.",
            'ru' => "Карта сайта $siteName: полный список разделов и страниц.",
            'el' => "Χάρτης ιστοτόπου $siteName: πλήρης λίστα ενοτήτων και σελίδων.",
        ],
    ];

    // Проверка: есть ли такая фраза и такой язык?
    if (isset($data[$key][$lang])) {
        return $data[$key][$lang];
    } elseif (isset($data[$key]['en'])) {
        return $data[$key]['en']; // Если языка нет, отдаем английский
    }

    return 'Translation missing';
}

// Регистрация шорткодов для удобства
add_shortcode('txt_read_more', function () {
    return get_site_translation('read_more');
});
add_shortcode('txt_not_found', function () {
    return get_site_translation('not_found');
});
add_shortcode('txt_toc', function () {
    return get_site_translation('toc');
});
add_shortcode('txt_reading_time', function () {
    return get_site_translation('reading_time');
});
add_shortcode('txt_mins', function () {
    return get_site_translation('mins');
});
add_shortcode('txt_kb_bets', function () {
    return get_site_translation('kb_bets');
});
add_shortcode('txt_legal_disclaimer', function () {
    return get_site_translation('legal_disclaimer');
});
add_shortcode('txt_cookie_notice', function () {
    return get_site_translation('cookie_notice');
});
add_shortcode('txt_expert_checked', function () {
    return get_site_translation('expert_checked');
});
add_shortcode('txt_affiliate_disclosure', function () {
    return get_site_translation('affiliate_disclosure');
});


// Включаем обработку шорткодов в заголовках и текстовых блоках Gutenberg
add_filter('render_block', function ($block_content, $block) {
    // Проверяем, есть ли шорткод в контенте блока
    if (strpos($block_content, '[') !== false) {
        return do_shortcode($block_content);
    }
    return $block_content;
}, 10, 2);

function get_responsible_gaming_block()
{
    $lang = substr(get_bloginfo('language'), 0, 2);

    // Получаем текст фразы
    $text = get_site_translation('help_text'); // Наша новая фраза
    // Получаем URL из вашего массива
    global $HELP_URLS;
    $url = isset($HELP_URLS[$lang]) ? $HELP_URLS[$lang] : $HELP_URLS['en'];

    // Для русского языка заменим "здесь" на ссылку, для остальных — их аналоги
    // Но проще всего обернуть всю фразу или последнее слово. 
    // Вот пример замены последнего слова на ссылку:

    $words = explode(' ', $text);
    $last_word = array_pop($words);
    $text_with_link = implode(' ', $words) . ' <a href="' . $url . '" target="_blank" rel="nofollow">' . $last_word . '</a>.';

    return $text_with_link;
}
